# Data set 1

data link
https://www.datos.gob.mx/dataset/datos_viales

In [153]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

data = pd.read_csv("data/Datos_viales_2013_2024.csv")
municipios = gpd.read_file("data/Mexico_mun_layer_simplified.shp")  # INEGI shapefile

# Create GeoDataFrame from your data
gdf = gpd.GeoDataFrame(
    data,
    geometry=gpd.points_from_xy(data.longitud, data.latitud),
    crs="EPSG:4326"
)

# Reproject to match shapefile CRS if needed
municipios = municipios.to_crs("EPSG:4326")

# Spatial join
result = gpd.sjoin(gdf, municipios[["CVEGEO", "NOMGEO", "geometry"]], how="left", predicate="within")
result = result.rename(columns={"NOMGEO": "municipio"})
result.drop(columns=["geometry", "index_right"])

/opt/anaconda3/envs/torch/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: data/Mexico_mun_layer_simplified.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,aa,bb,cc,k,d,latitud,longitud,ejercicio,CVEGEO,municipio
0,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,6827.0,6.1,...,96.1,0.6,3.3,0.071,0.520,22.146662,-102.290244,2024,01006,Pabellón de Arteaga
1,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,811.0,3.5,...,86.3,4.5,9.2,0.074,0.518,22.146570,-102.290230,2024,01006,Pabellón de Arteaga
2,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7399.0,6.1,...,95.9,0.6,3.5,0.069,0.520,22.146735,-102.290236,2024,01006,Pabellón de Arteaga
3,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,753.0,4.2,...,85.8,4.3,9.9,0.097,0.518,22.146823,-102.290227,2024,01006,Pabellón de Arteaga
4,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6377.0,2.8,...,93.3,0.8,5.9,0.074,0.537,22.147018,-102.285324,2024,01006,Pabellón de Arteaga
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146391,Zacatecas,Tepatitlan-Jaralillo,146.0,MEX-JAL-ZAC,Lim_Edos_Term_Jal_Ppia_Zac,83.5,NaN,NaN,sin dato,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,NaN,NaN
146392,Zacatecas,Tepatitlan-Jaralillo,146.0,MEX-JAL-ZAC,Lim_Edos_Term_Zac_Ppia_Jal,106.0,NaN,NaN,sin dato,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,NaN,NaN
146393,Zacatecas,Tepatitlan-Jaralillo,146.0,MEX-JAL-ZAC,Teocaltiche,111.0,1.0,0.0,3473.0,1.1,...,88.0,0.8,11.2,0.100,0.500,21.426000,-102.590000,2013,14091,Teocaltiche
146394,Zacatecas,Tepatitlan-Jaralillo,146.0,MEX-JAL-ZAC,Teocaltiche,111.0,3.0,0.0,3318.0,1.3,...,89.6,0.5,9.9,0.100,0.500,21.455000,-102.556000,2013,14091,Teocaltiche
146395,Zacatecas,Tepatitlan-Jaralillo,146.0,MEX-JAL-ZAC,T_C_Leon-Aguascalientes,157.0,1.0,0.0,2413.0,1.4,...,82.5,1.1,16.4,0.100,0.500,21.643000,-102.279000,2013,14035,Encarnación de Díaz

In [154]:
result.head()

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,CVEGEO,municipio
0,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,6827.0,6.1,...,3.3,0.071,0.520,22.146662,-102.290244,2024,POINT (-102.29024 22.14666),5.0,01006,Pabellón de Arteaga
1,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,811.0,3.5,...,9.2,0.074,0.518,22.146570,-102.290230,2024,POINT (-102.29023 22.14657),5.0,01006,Pabellón de Arteaga
2,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7399.0,6.1,...,3.5,0.069,0.520,22.146735,-102.290236,2024,POINT (-102.29024 22.14674),5.0,01006,Pabellón de Arteaga
3,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,753.0,4.2,...,9.9,0.097,0.518,22.146823,-102.290227,2024,POINT (-102.29023 22.14682),5.0,01006,Pabellón de Arteaga
4,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6377.0,2.8,...,5.9,0.074,0.537,22.147018,-102.285324,2024,POINT (-102.28532 22.14702),5.0,01006,Pabellón de Arteaga

In [155]:
print(result.isna().sum())
print(len(result))

estado                 0
carretera              0
clave                  0
ruta                   0
punto_generador        0
km                     0
te                 17110
sc                 17112
tdpa                   0
m                  17150
a                  17150
b                  17150
c2                 17150
c3                 17150
t3s2               17150
t3s3               17150
t3s2r4             17150
otros              17150
aa                 17150
bb                 17150
cc                 17150
k                  17150
d                  17140
latitud            17160
longitud           17173
ejercicio              0
geometry               0
index_right        27992
CVEGEO             27992
municipio          27992
dtype: int64
147108

In [156]:
# Are the missing-municipio rows random, or clustered?
print(result[result["municipio"].isna()]["estado"].value_counts())
print(result[result["municipio"].isna()]["ejercicio"].value_counts())

estado
Mexico                 2452
Veracruz               1610
Puebla                 1582
Jalisco                1279
Michoacan              1091
Hidalgo                1080
Guanajuato             1065
Morelos                 994
Zacatecas               963
Tlaxcala                961
San Luis Potosi         950
Coahuila                907
Chiapas                 889
Guerrero                871
Tamaulipas              859
Nuevo Leon              857
Oaxaca                  847
Tabasco                 776
Aguascalientes          742
Ciudad de Mexico        736
Yucatan                 657
Queretaro               649
Colima                  627
Chihuahua               601
Sinaloa                 579
Quintana Roo            539
Nayarit                 521
Baja California         499
Sonora                  494
Campeche                472
Baja California Sur     472
Durango                 371
Name: count, dtype: int64
ejercicio
2015    11295
2022     1692
2023     1684
2021     1682
2020     1669
2019     1523
2018     1511
2016     1468
2017     1442
2013     1398
2014     1387
2024     1241
Name: count, dtype: int64

In [157]:
## missing municipio rows are well balanced so we drop NA rows
result = result.dropna()

In [158]:
print(result.isna().sum())
print(len(result))

estado             0
carretera          0
clave              0
ruta               0
punto_generador    0
km                 0
te                 0
sc                 0
tdpa               0
m                  0
a                  0
b                  0
c2                 0
c3                 0
t3s2               0
t3s3               0
t3s2r4             0
otros              0
aa                 0
bb                 0
cc                 0
k                  0
d                  0
latitud            0
longitud           0
ejercicio          0
geometry           0
index_right        0
CVEGEO             0
municipio          0
dtype: int64
119111

In [159]:
result.head()

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,CVEGEO,municipio
0,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,6827.0,6.1,...,3.3,0.071,0.520,22.146662,-102.290244,2024,POINT (-102.29024 22.14666),5.0,01006,Pabellón de Arteaga
1,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,811.0,3.5,...,9.2,0.074,0.518,22.146570,-102.290230,2024,POINT (-102.29023 22.14657),5.0,01006,Pabellón de Arteaga
2,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7399.0,6.1,...,3.5,0.069,0.520,22.146735,-102.290236,2024,POINT (-102.29024 22.14674),5.0,01006,Pabellón de Arteaga
3,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,753.0,4.2,...,9.9,0.097,0.518,22.146823,-102.290227,2024,POINT (-102.29023 22.14682),5.0,01006,Pabellón de Arteaga
4,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6377.0,2.8,...,5.9,0.074,0.537,22.147018,-102.285324,2024,POINT (-102.28532 22.14702),5.0,01006,Pabellón de Arteaga

In [160]:
result['municipio'].nunique()

1255

In [161]:
# drop 2024 data
result = result[result['ejercicio'] != 2024]

result.head()

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,CVEGEO,municipio
10326,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,7704.0,6.2,...,3.2,0.064,0.506,22.146715,-102.289490,2023,POINT (-102.28949 22.14672),5.0,01006,Pabellón de Arteaga
10327,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,742.0,4.0,...,9.1,0.106,0.507,22.146619,-102.289521,2023,POINT (-102.28952 22.14662),5.0,01006,Pabellón de Arteaga
10328,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7892.0,6.4,...,3.7,0.066,0.506,22.146790,-102.289475,2023,POINT (-102.28948 22.14679),5.0,01006,Pabellón de Arteaga
10329,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,762.0,3.8,...,9.5,0.077,0.507,22.146886,-102.289361,2023,POINT (-102.28936 22.14689),5.0,01006,Pabellón de Arteaga
10330,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6460.0,2.8,...,5.9,0.076,0.515,22.147082,-102.284616,2023,POINT (-102.28462 22.14708),5.0,01006,Pabellón de Arteaga

covariates to use 
- tdpa: average daily traffic (collapse into mean for each municipality)
- punto_generador: traffic generation point (count of unique stations)
vehicles: (percentage share of traffic composition?)
- m: motorcycles
- a: automobiles
- b: buses
- c2: 2 axle truck
- c3: 3 acle truck
- t3s2: tractor trailer (3 axle tractor, 2 axle semi)
- t3s3: tractor trailer (3 axle, 3 axle semi)
- t3s2r4: tractor trailer with dolly (3, 2, 4 axles)
- aa: automobiles adjusted
- bb: buses adjusted
- cc: trucks adjusted

In [162]:
# checking for punto_generador counts per municipio using Calvillo just to check 
result[result['municipio'] == "Calvillo"]

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,CVEGEO,municipio
10345,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Izq_Malpaso,45.1,1.0,0.0,8112.0,2.5,...,4.5,0.118,0.502,21.880894,-102.653297,2023,POINT (-102.6533 21.88089),6.0,01003,Calvillo
10346,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,1.0,10974.0,4.0,...,4.6,0.083,0.527,21.863580,-102.692551,2023,POINT (-102.69255 21.86358),6.0,01003,Calvillo
10347,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,2.0,12222.0,3.7,...,4.5,0.079,0.527,21.863517,-102.692414,2023,POINT (-102.69241 21.86352),6.0,01003,Calvillo
10348,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,1.0,5040.0,3.3,...,4.0,0.079,0.509,21.834688,-102.747348,2023,POINT (-102.74735 21.83469),6.0,01003,Calvillo
10349,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,2.0,5219.0,2.3,...,3.5,0.072,0.509,21.834552,-102.747277,2023,POINT (-102.74728 21.83455),6.0,01003,Calvillo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146062,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,1.0,8407.0,1.0,...,6.9,0.100,0.500,21.864000,-102.692000,2013,POINT (-102.692 21.864),6.0,01003,Calvillo
146063,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,2.0,8824.0,0.9,...,7.8,0.100,0.500,21.864000,-102.692000,2013,POINT (-102.692 21.864),6.0,01003,Calvillo
146064,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,1.0,4636.0,1.4,...,8.4,0.100,0.500,21.839000,-102.740000,2013,POINT (-102.74 21.839),6.0,01003,Calvillo
146065,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,2.0,4706.0,1.2,...,9.3,0.100,0.500,21.839000,-102.740000,2013,POINT (-102.74 21.839),6.0,01003,Calvillo
146066,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Jaltiche_de_Abajo,63.8,3.0,0.0,5001.0,0.6,...,10.5,0.100,0.500,21.771000,-102.804000,2013,POINT (-102.804 21.771),6.0,01003,Calvillo

In [163]:
result[["m","a","b","c2","c3","t3s2","t3s3","t3s2r4","otros"]].sum(axis=1).describe()

count    109982.000000
mean        100.001454
std           0.184135
min          99.600000
25%         100.000000
50%         100.000000
75%         100.000000
max         132.700000
dtype: float64

In [164]:
# collapsing tdpa mean by municipality 

result["tdpa"] = pd.to_numeric(result["tdpa"], errors = "coerce")
result["tdpa_mean"] = result.groupby("municipio")["tdpa"].transform("mean")


print(result.head())
print(result.tail())

               estado                     carretera   clave     ruta  \
10326  Aguascalientes  Acceso_a_Pabellon_de_Arteaga  1113.0  MEX-045
10327  Aguascalientes  Acceso_a_Pabellon_de_Arteaga  1113.0  MEX-045
10328  Aguascalientes  Acceso_a_Pabellon_de_Arteaga  1113.0  MEX-045
10329  Aguascalientes  Acceso_a_Pabellon_de_Arteaga  1113.0  MEX-045
10330  Aguascalientes  Acceso_a_Pabellon_de_Arteaga  1113.0  MEX-045

                         punto_generador   km   te   sc    tdpa    m  ...  \
10326  T_C_Aguascalientes-Zacatecas_Alta  0.0  3.0  1.0  7704.0  6.2  ...
10327  T_C_Aguascalientes-Zacatecas_Baja  0.0  3.0  1.0   742.0  4.0  ...
10328  T_C_Aguascalientes-Zacatecas_Alta  0.0  3.0  2.0  7892.0  6.4  ...
10329  T_C_Aguascalientes-Zacatecas_Baja  0.0  3.0  2.0   762.0  3.8  ...
10330                Pabellon_de_Arteaga  1.8  1.0  1.0  6460.0  2.8  ...

           k      d    latitud    longitud  ejercicio  \
10326  0.064  0.506  22.146715 -102.289490       2023
10327  0.106  0.507  22.146619 -102.289521       2023
10328  0.066  0.506  22.146790 -102.289475       2023
10329  0.077  0.507  22.146886 -102.289361       2023
10330  0.076  0.515  22.147082 -102.284616       2023

                          geometry  index_right  CVEGEO            municipio  \
10326  POINT (-102.28949 22.14672)          5.0   01006  Pabellón de Arteaga
10327  POINT (-102.28952 22.14662)          5.0   01006  Pabellón de Arteaga
10328  POINT (-102.28948 22.14679)          5.0   01006  Pabellón de Arteaga
10329  POINT (-102.28936 22.14689)          5.0   01006  Pabellón de Arteaga
10330  POINT (-102.28462 22.14708)          5.0   01006  Pabellón de Arteaga

         tdpa_mean
10326  7369.055556
10327  7369.055556
10328  7369.055556
10329  7369.055556
10330  7369.055556

[5 rows x 31 columns]
           estado             carretera  clave         ruta  \
146389  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146390  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146393  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146394  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146395  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC

                    punto_generador      km   te   sc    tdpa    m  ...    k  \
146389  Yahualica_de_Gonzalez_Gallo   57.40  3.0  2.0  1419.0  2.2  ...  0.1
146390             T_Der_Mexticacan   72.45  3.0  0.0  2136.0  1.7  ...  0.1
146393                  Teocaltiche  111.00  1.0  0.0  3473.0  1.1  ...  0.1
146394                  Teocaltiche  111.00  3.0  0.0  3318.0  1.3  ...  0.1
146395      T_C_Leon-Aguascalientes  157.00  1.0  0.0  2413.0  1.4  ...  0.1

          d  latitud  longitud  ejercicio                 geometry  \
146389  0.5   21.203  -102.886       2013  POINT (-102.886 21.203)
146390  0.5   21.255  -102.803       2013  POINT (-102.803 21.255)
146393  0.5   21.426  -102.590       2013   POINT (-102.59 21.426)
146394  0.5   21.455  -102.556       2013  POINT (-102.556 21.455)
146395  0.5   21.643  -102.279       2013  POINT (-102.279 21.643)

        index_right  CVEGEO                    municipio    tdpa_mean
146389        566.0   14118  Yahualica de González Gallo  1763.978723
146390        631.0   14060                   Mexticacán  1143.214286
146393        605.0   14091                  Teocaltiche  3449.089286
146394        605.0   14091                  Teocaltiche  3449.089286
146395        654.0   14035          Encarnación de Díaz  5957.179941

[5 rows x 31 columns]

In [165]:
# punto_generador: traffic generation point (count of unique stations)

result["punto_generador_count"] = result.groupby("municipio")["punto_generador"].transform("nunique")
print(result.tail())

           estado             carretera  clave         ruta  \
146389  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146390  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146393  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146394  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146395  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC

                    punto_generador      km   te   sc    tdpa    m  ...    d  \
146389  Yahualica_de_Gonzalez_Gallo   57.40  3.0  2.0  1419.0  2.2  ...  0.5
146390             T_Der_Mexticacan   72.45  3.0  0.0  2136.0  1.7  ...  0.5
146393                  Teocaltiche  111.00  1.0  0.0  3473.0  1.1  ...  0.5
146394                  Teocaltiche  111.00  3.0  0.0  3318.0  1.3  ...  0.5
146395      T_C_Leon-Aguascalientes  157.00  1.0  0.0  2413.0  1.4  ...  0.5

        latitud  longitud  ejercicio                 geometry  index_right  \
146389   21.203  -102.886       2013  POINT (-102.886 21.203)        566.0
146390   21.255  -102.803       2013  POINT (-102.803 21.255)        631.0
146393   21.426  -102.590       2013   POINT (-102.59 21.426)        605.0
146394   21.455  -102.556       2013  POINT (-102.556 21.455)        605.0
146395   21.643  -102.279       2013  POINT (-102.279 21.643)        654.0

        CVEGEO                    municipio    tdpa_mean  \
146389   14118  Yahualica de González Gallo  1763.978723
146390   14060                   Mexticacán  1143.214286
146393   14091                  Teocaltiche  3449.089286
146394   14091                  Teocaltiche  3449.089286
146395   14035          Encarnación de Díaz  5957.179941

        punto_generador_count
146389                      2
146390                      2
146393                      1
146394                      1
146395                     10

[5 rows x 32 columns]

In [166]:
vehicle_cols = ["m", "a", "b", "c2", "c3", "t3s2", "t3s3", "t3s2r4", "otros", "aa", "bb", "cc"]

for col in vehicle_cols:
    result[col] = pd.to_numeric(result[col], errors="coerce")
    result[f"{col}_mean"] = result.groupby("municipio")[col].transform("mean")

In [167]:
print(result.tail())

           estado             carretera  clave         ruta  \
146389  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146390  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146393  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146394  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC
146395  Zacatecas  Tepatitlan-Jaralillo  146.0  MEX-JAL-ZAC

                    punto_generador      km   te   sc    tdpa    m  ...  \
146389  Yahualica_de_Gonzalez_Gallo   57.40  3.0  2.0  1419.0  2.2  ...
146390             T_Der_Mexticacan   72.45  3.0  0.0  2136.0  1.7  ...
146393                  Teocaltiche  111.00  1.0  0.0  3473.0  1.1  ...
146394                  Teocaltiche  111.00  3.0  0.0  3318.0  1.3  ...
146395      T_C_Leon-Aguascalientes  157.00  1.0  0.0  2413.0  1.4  ...

          b_mean   c2_mean   c3_mean  t3s2_mean  t3s3_mean  t3s2r4_mean  \
146389  0.951064  5.091489  0.963830   0.444681   0.334043     0.085106
146390  0.889286  9.914286  2.014286   0.967857   0.496429     0.078571
146393  1.585714  7.414286  1.391071   1.291071   0.682143     0.135714
146394  1.585714  7.414286  1.391071   1.291071   0.682143     0.135714
146395  4.177581  6.688201  2.923009   8.468732   2.030088     3.539528

        otros_mean    aa_mean   bb_mean    cc_mean
146389    0.134043  91.995745  0.951064   7.053191
146390    0.092857  85.546429  0.889286  13.564286
146393    0.142857  87.357143  1.585714  11.057143
146394    0.142857  87.357143  1.585714  11.057143
146395    0.725959  71.446903  4.177581  24.375516

[5 rows x 44 columns]

In [168]:
result.columns.tolist()

['estado',
 'carretera',
 'clave',
 'ruta',
 'punto_generador',
 'km',
 'te',
 'sc',
 'tdpa',
 'm',
 'a',
 'b',
 'c2',
 'c3',
 't3s2',
 't3s3',
 't3s2r4',
 'otros',
 'aa',
 'bb',
 'cc',
 'k',
 'd',
 'latitud',
 'longitud',
 'ejercicio',
 'geometry',
 'index_right',
 'CVEGEO',
 'municipio',
 'tdpa_mean',
 'punto_generador_count',
 'm_mean',
 'a_mean',
 'b_mean',
 'c2_mean',
 'c3_mean',
 't3s2_mean',
 't3s3_mean',
 't3s2r4_mean',
 'otros_mean',
 'aa_mean',
 'bb_mean',
 'cc_mean']

In [169]:
final_df = result[['CVEGEO', 'municipio', 'tdpa_mean', 'punto_generador_count', 'm_mean', 'a_mean', 'b_mean', 'c2_mean', 'c3_mean', 't3s2_mean', 't3s3_mean', 't3s2r4_mean', 'otros_mean', 'aa_mean', 'bb_mean', 'cc_mean']]

final_df = final_df.groupby("municipio").first().reset_index()

print(final_df.head())

print(len(final_df))

                   municipio CVEGEO    tdpa_mean  punto_generador_count  \
0                    Abasolo  05001  9443.580645                      5
1                 Acacoyagua  07001  3865.750000                      1
2                    Acajete  21001  7085.750000                      1
3  Acambay de Ruíz Castañeda  15001  5410.750000                      5
4                    Acanceh  31002  3394.594203                      3

      m_mean     a_mean    b_mean    c2_mean   c3_mean  t3s2_mean  t3s3_mean  \
0   1.636022  67.756989  3.809677  10.224194  3.764516   7.797312   2.320968
1   9.640000  66.672500  3.175000   6.490000  2.030000   6.732500   1.495000
2   2.016667  72.025000  1.941667  12.766667  2.525000   5.775000   1.758333
3   1.774479  68.163542  5.036458   5.634896  3.037500  10.324479   2.116667
4  15.892754  71.257971  1.189855   6.585507  1.613043   1.885507   0.604348

   t3s2r4_mean  otros_mean    aa_mean   bb_mean    cc_mean
0     2.110215    0.580108  69.393011  3.809677  26.797312
1     3.235000    0.530000  76.312500  3.175000  20.512500
2     0.641667    0.550000  74.041667  1.941667  24.016667
3     3.248958    0.663021  69.938021  5.036458  25.025521
4     0.708696    0.262319  87.150725  1.189855  11.659420
1253

In [170]:
print(final_df["CVEGEO"].nunique())
print(final_df["municipio"].nunique())

1253
1253

In [171]:
final_df.to_csv("roads1.csv", index=False)

# Data set 2

data link
https://www.datos.gob.mx/dataset/capacidad_niveles_servicio_red_carretera_federal

https://www.inegi.org.mx/app/biblioteca/ficha.html?upc=794551132166

Claude notation

The highway CSV has no municipality column — it only knows which road segment it is and what state it's in. The core idea is to extract place names hidden in the text fields and look them up in a municipality directory.

The approach has three stages:

1. Mining place names from text
Highway segment names like "Monterrey-Saltillo" or "Acambaro - Celaya" are essentially origin-destination pairs. The place names at either end of a segment are usually towns or cities, which are often (though not always) municipality names. The STRIP regex cleans out highway jargon (T. Izq., Lim. Edos., etc.) that looks like text but isn't a place, leaving just the meaningful geographic tokens.

2. Fuzzy matching against a known list
Rather than looking up exact strings (which would fail on accents, abbreviations, and spelling variants), you compare each extracted token against every municipality name in the INEGI catalog using a similarity score. The token_sort_ratio scorer is forgiving about word order and minor spelling differences. You get back the best-matching municipality and a confidence score, and only accept matches above a threshold.

3. Resolving ambiguity with a hierarchy
The same city name can appear in multiple states, so the code searches within the segment's state first (more precise), and only falls back to a nationwide search if nothing matches locally. Manual corrections handle the cases where fuzzy matching fundamentally can't work — abbreviations like "Cd. Valles" or localities like "Zihuatanejo" whose municipality has a different official name.

The fundamental limitation is that a road segment is a line, not a point — it can cross multiple municipalities, and you're assigning it to just one based on whichever place name matched best. You're also only recovering municipality identity from the endpoints named in the segment label, not from the segment's actual geographic path. This means the resulting CVE_MUN is an approximation: good enough for aggregating infrastructure covariates to the municipality level, but not a precise spatial attribution.

Honestly, the match quality is mixed and varies systematically by case type. Here's a realistic breakdown:

High confidence (~correct most of the time)

Segments where tramo or carretera starts with a major city name that is also the municipality name — "Acambaro - Celaya", "Monterrey - Saltillo". These are likely correct.
Manual corrections (corrections dict) — those were hand-verified, so score 100 means it's right.
High-scoring within-state matches (score ≥ 90) where the place name is unambiguous in that state.

Moderate confidence (~right but not guaranteed)

Scores in the 75–89 range — fuzzy matching at this level catches accent/spelling variants but also produces false positives, especially for short or common-sounding names.
Nationwide fallback matches — correct when the city is unambiguous nationally (e.g. "Monterrey"), but risky for common names that appear in multiple states (e.g. "San Juan", "Santa María", "Guadalupe").

Low confidence / likely wrong

Segment crosses multiple municipalities — you assigned one endpoint's municipality, but a 50km segment may pass through 4 or 5. This is structural, not a code bug.
City ≠ municipality name — "Zihuatanejo" is in municipality "José Azueta". You caught some with the corrections dict but there are others you didn't (e.g. "Cancún" → "Benito Juárez", "Los Cabos", "Valle de México").
Threshold 70 false positives — at this threshold, short names like "Rayon", "Uman", "Conkal" could match the wrong municipality in a different state during the nationwide fallback.
Infrastructure labels that survived STRIP — "Periférico de Mérida" matching to "Mérida" is probably fine, but "Libramiento" or "Ramal" matching anything is wrong.

Bottom line for your purposes

For a smoothness battery in an RDD, what matters is not that every segment is perfectly geocoded, but that misassignment is random with respect to the running variable (your reconstructed selection index). If mismatches are concentrated in certain highway types or regions that correlate with the selection score, they could contaminate the balance test. Otherwise, they just add noise and attenuate your covariate balance statistics toward zero — which is conservative, not invalidating.

The safest approach is to only use municipality-level aggregates where you have sufficient segment coverage (e.g., at least 3–5 matched segments per municipality), flag municipalities with low coverage in your technical appendix, and note that the attribution is approximate.

In [172]:
from rapidfuzz import process, fuzz

# highway data
df = pd.read_csv("data/capacidad_niveles_servicio_red_carretera_federal.csv")

# INEGI municipality catalog
mun_cat = pd.read_csv("data/catun_municipio/AGEEML_20268211656753_utf8.csv", dtype=str)

# find state names in df that don't match INEGI official names
print(set(df["estado"]) - set(mun_cat["NOM_ENT"].unique()))

{'Veracruz', 'Yucatan', 'Ciudad de Mexico', 'Coahuila', 'Mexico', 'San Luis Potosi', 'Nuevo Leon', 'Michoacan', 'Queretaro'}

In [173]:
# state name fixes
estado_fixes = {
    "Veracruz":        "Veracruz de Ignacio de la Llave",
    "Yucatan":         "Yucatán",
    "Ciudad de Mexico": "Ciudad de México",
    "Coahuila":        "Coahuila de Zaragoza",
    "Mexico":          "México",
    "San Luis Potosi": "San Luis Potosí",
    "Nuevo Leon":      "Nuevo León",
    "Michoacan":       "Michoacán de Ocampo",
    "Queretaro":       "Querétaro",
}

# estado_ent new column with corrected names
df["estado_ent"] = df["estado"].replace(estado_fixes)

print(set(df["estado_ent"]) - set(mun_cat["NOM_ENT"].unique()))

set()

In [174]:
import re
import unicodedata

# strip accents
def strip_accents(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn')

# Expanded strip pattern — now also catches T.C., X., and Lim. Edos fully
STRIP = r"""(?ix)
    T\.\s*C\.\s*                    |   # T. C. (troncal conexión)
    T\.\s*[IiDd][zqr][q\.]?\s*     |   # T. Izq., T. Der.
    X\.\s*C\.\s*                    |   # X. C.
    X\.\s+                          |   # X. (standalone)
    Lim\.\s*Edos?\.?[^-]*          |   # Lim. Edos. Term. ... (whole phrase)
    Plaza\s+de\s+Cobro[^-]*        |
    Libramiento\s+[^-]*de\s+       |
    Entronque[^-]*                  |
    Ent\.[^-]*                      |
    Acceso[^-]*                     |
    Ppia\.[^-]*                     |
    Term\.[^-]*
"""

def extract_places(s):
    cleaned = re.sub(STRIP, "", s)  # remove jargon (like TC etc)
    parts = [p.strip() for p in re.split(r"[-–]", cleaned) if p.strip()]
    return [p for p in parts if len(p) > 3 and not re.match(r"^\d", p)]


# apply extract places to both tramo (stretch) and carretera (road)
df["_places"]          = df["tramo"].apply(extract_places)
df["_carretera_places"] = df["carretera"].apply(extract_places)  # now uses STRIP too
df["_all_places"]       = df["_places"] + df["_carretera_places"]




# Normalize mun catalog — strip accents for matching, keep originals for output
mun_cat["_NOM_MUN_norm"] = mun_cat["NOM_MUN"].apply(lambda s: strip_accents(s).upper())

# Rebuild state_muns using accent-stripped keys
# building dictionary
state_muns = (
    mun_cat
    .groupby("NOM_ENT")
    .apply(lambda g: dict(zip(g["_NOM_MUN_norm"], g["CVEGEO"])))
    .to_dict()
)


# states missing after estado_fixes are excluded here
estado_map = {row: row for row in df["estado_ent"].unique()
              if row in mun_cat["NOM_ENT"].values}



# Nationwide lookup (all states collapsed)
# used when within-state search fails
all_muns = dict(zip(mun_cat["_NOM_MUN_norm"], mun_cat["CVEGEO"]))

corrections = {
    "CD. VALLES":              "24035",  # Ciudad Valles, SLP
    "TUXPAM":                  "30185",  # Tuxpan, Veracruz
    "ZIHUATANEJO":             "12038",  # José Azueta, Guerrero
    "PUERTO JUAREZ":           "23005",  # Benito Juárez (Cancún), Q. Roo
    "PERIFERICO DE MERIDA":    "31050",  # Mérida, Yucatán
    "PERIFERICO DE SAN LUIS POTOSI": "24028",  # SLP capital
    "VENTA DE CARPIO":         "15033",  # Ecatepec, México
    "TIHUATLAN":               "30175",  # Tihuatlán, Veracruz
    "CD. JUAREZ":              "08037",  # Juárez, Chihuahua
}



def match_place_to_mun(place, estado, threshold=70):
    ent = estado_map.get(estado)
    query = strip_accents(place).upper()
    
    if query in corrections:
        return corrections[query], 100
    
    # First try within-state (more precise)
    if ent:
        candidates = state_muns.get(ent, {})
        result = process.extractOne(query, list(candidates.keys()),
                                    scorer=fuzz.token_sort_ratio)
        if result and result[1] >= threshold:
            return candidates[result[0]], result[1]
    
    # Fall back to nationwide search
    result = process.extractOne(query, list(all_muns.keys()),
                                scorer=fuzz.token_sort_ratio)
    if result and result[1] >= threshold:
        return all_muns[result[0]], result[1]
    return None, None

/var/folders/gy/z4d7vxps0499h9pzspv7jx1c0000gn/T/ipykernel_28667/3481632176.py:47: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: dict(zip(g["_NOM_MUN_norm"], g["CVEGEO"])))

In [175]:
# Resolve each segment to a CVEGEO 
# for each road segment, tries every extracted place name and keeps whiever one produces the highest confidence municipality match. one CVE_MUN per segment
records = []
for _, row in df.iterrows():
    best_cvegeo, best_score = None, 0
    for place in row["_all_places"]:
        cvegeo, score = match_place_to_mun(place, row["estado"])
        if score and score > best_score:
            best_cvegeo, best_score = cvegeo, score
    records.append({"consecutivo": row["consecutivo"],
                    "CVE_MUN": best_cvegeo,
                    "match_score": best_score})

matches = pd.DataFrame(records)

df = df.merge(matches, on="consecutivo", how="left")

# Audit: how many got assigned?
print(df["CVE_MUN"].notna().value_counts())
# Review low-confidence matches
df[df["match_score"].between(75, 85)][["tramo", "estado", "CVE_MUN", "match_score"]].head(20)

CVE_MUN
True     3322
False      46
Name: count, dtype: int64

,tramo,estado,CVE_MUN,match_score
80,T. Izq. Tempoal de Sanchez (Acceso 1)-T. Izq. ...,Veracruz,10002,76.923077
157,Ent. La Zarca-El Palmito,Durango,14070,77.777778
281,Ciudad Altamirano-T. Der. Zirandaro,Guerrero,28003,75.000000
283,Ciudad Constitucion-T. Der. Benito Juarez,Baja California Sur,32004,76.470588
284,T. Der. Benito Juarez-Puerto San Carlos,Baja California Sur,32004,76.470588
315,Plaza de Cobro Esperanza-T. Der. Estacion Corral,Sonora,14117,75.000000
316,T. Der. Estacion Corral-T. Izq. Bacum,Sonora,26012,83.333333
317,T. Izq. Bacum-Vicam,Sonora,26012,83.333333
318,Vicam-T. Izq. Potam,Sonora,14117,75.000000
319,T. Izq. Potam-T. Der. Libramiento de Guaymas,Sonora,14117,75.000000
387,T. C. Ramal a Compostela (Cuota)-Plaza de Cobr...,Nayarit,07028,84.210526
388,Plaza de Cobro Compostela-T. Der. Compostela,Nayarit,07028,84.210526
418,T. Der. El Palmar-Chichihualco,Guerrero,30180,75.000000
419,Chilpancingo-T. Der. Tixtla de Guerrero,Guerrero,12061,81.818182
420,T. Der. Tixtla de Guerrero-T. Izq. Almolonga,Guerrero,12061,81.818182
499,Lim. Edos. Term. Jal. Ppia. Col.-Atenquique,Jalisco,14099,76.923077
500,Atenquique-T. Izq. Tepozal y Nevado de Colima,Jalisco,14099,76.923077
501,T. Izq. Tepozal y Nevado de Colima-T. Der. Zap...,Jalisco,14099,76.923077
502,T. Der. Zapotiltic-Cd. Guzman,Jalisco,14099,76.923077
742,Michapa-Lim. Edos. Term. Mor. Ppia. Gro.,Morelos,30052,80.000000

In [176]:
# What are the extracted place tokens for unmatched segments?
unmatched = df[df["CVE_MUN"].isna()]
all_places = [p for places in unmatched["_places"] for p in places]
pd.Series(all_places).value_counts().head(40)

T. Der. Hool                         2
Ciudad Hidalgo                       2
Lim. de Edos.                        2
Poblado Chico                        2
T. Der. El Fuerte                    2
Circuito Exterior Mexiquense         2
AIFA                                 2
T. Der. Lib. Noreste de Zacatecas    2
. Ramonal                            2
T. Der. Fundicion                    2
T. Der. Cd. Obregon (Cuota)          2
. Santa Eulalia                      2
. Av. Escenica                       1
Tejocotal                            1
Nuevo Necaxa (Cuota)                 1
T. Ramal a Avila Camacho             1
Penon                                1
Ramal a Cerralvo                     1
Cd. Constitucion                     1
Ramal a el Quemado                   1
Hool                                 1
Melchor Muzquiz                      1
Ruiz Cortines                        1
T Der. Aduana Santa Elena            1
Subteniente Lopez                    1
T. Der. Santa Maria Poniente         1
Polyuc                               1
Ramal al AIFA (Cuota)                1
Boquillas del Carmen                 1
. Camahuiroa                         1
Cd. Obregon                          1
Ciudad Acuna                         1
Presa de La Amistad                  1
Laguna Salada                        1
El Retono                            1
T. Der. Ignacio Lopez Rayon          1
Parador Punta Prieta                 1
Bahia de Los Angeles                 1
T. Der. Mexcaltitan                  1
Playa Los Corchos                    1
Name: count, dtype: int64

In [185]:
print(len(df))

print(df["CVE_MUN"].nunique())

print(df.tail())

3368
666
      consecutivo  edo     estado  idred      red operacion  \
3363         3364   16  Michoacan      1  Federal     Libre
3364         3365   16  Michoacan      1  Federal     Libre
3365         3366   16  Michoacan      1  Federal     Libre
3366         3367   16  Michoacan      1  Federal     Libre
3367         3368   16  Michoacan      1  Federal     Libre

     clasificacion_carretera                   carretera  \
3363                       D  Zitacuaro - Cd. Altamirano
3364                       D  Zitacuaro - Cd. Altamirano
3365                       D  Zitacuaro - Cd. Altamirano
3366                       D  Zitacuaro - Cd. Altamirano
3367                       D  Zitacuaro - Cd. Altamirano

                                        tramo  km_inicial  ...  \
3363               San Cayetano-Benito Juarez        3.60  ...
3364                  Benito Juarez-Tiquicheo       26.06  ...
3365                        Tiquicheo-Huetamo      104.50  ...
3366                        Huetamo-San Lucas      174.60  ...
3367  San Lucas-T. C. Toluca - Cd. Altamirano      193.80  ...

               estado_ent                              _places  \
3363  Michoacán de Ocampo        [San Cayetano, Benito Juarez]
3364  Michoacán de Ocampo           [Benito Juarez, Tiquicheo]
3365  Michoacán de Ocampo                 [Tiquicheo, Huetamo]
3366  Michoacán de Ocampo                 [Huetamo, San Lucas]
3367  Michoacán de Ocampo  [San Lucas, Toluca, Cd. Altamirano]

                _carretera_places  \
3363  [Zitacuaro, Cd. Altamirano]
3364  [Zitacuaro, Cd. Altamirano]
3365  [Zitacuaro, Cd. Altamirano]
3366  [Zitacuaro, Cd. Altamirano]
3367  [Zitacuaro, Cd. Altamirano]

                                            _all_places  CVE_MUN  match_score  \
3363  [San Cayetano, Benito Juarez, Zitacuaro, Cd. A...    32004        100.0
3364  [Benito Juarez, Tiquicheo, Zitacuaro, Cd. Alta...    32004        100.0
3365    [Tiquicheo, Huetamo, Zitacuaro, Cd. Altamirano]    16038        100.0
3366    [Huetamo, San Lucas, Zitacuaro, Cd. Altamirano]    16038        100.0
3367  [San Lucas, Toluca, Cd. Altamirano, Zitacuaro,...    16077        100.0

     longitud_sum  carriles_mean is_cuota  share_cuota
3363        163.6            2.0        0          0.0
3364        163.6            2.0        0          0.0
3365         89.3            2.0        0          0.0
3366         89.3            2.0        0          0.0
3367         20.7            2.0        0          0.0

[5 rows x 35 columns]

## var translations
consecutivo → record/row number
edo → state code (abbreviated)
estado → state name
idred → network ID
red → road network type (federal, state, etc.)
operacion → operation type (free/toll)
clasificacion_carretera → highway classification
carretera → highway name/number
tramo → road segment
km_inicial → starting kilometer
km_final → ending kilometer
longitud → segment length
tdpa → average annual daily traffic
vhp → peak hour volume (volumen horario de proyecto)
b → buses
c → trucks
tipo_terreno → terrain type (flat, rolling, mountainous)
carriles → number of lanes
fs_a → level of service factor A
fs_b → level of service factor B
fs_c → level of service factor C
fs_d → level of service factor D
fs_e → level of service factor E
nivel_servicio → level of service (A–E)
ejercicio → fiscal/survey year


potential covariates
- longitud_sum: total road length km in municipality
- carriles_mean: number of lanes
- share_cuota: fraction of segments that have paid tolls

In [ ]:
# sum up road segments per municipality

df["longitud_sum"] = df.groupby("CVE_MUN")["longitud"].transform("sum")
print(df.head())

   consecutivo  edo      estado  idred      red operacion  \
0            1   11  Guanajuato      1  Federal     Libre
1            2   11  Guanajuato      1  Federal     Libre
2            3   11  Guanajuato      1  Federal     Libre
3            4   11  Guanajuato      1  Federal     Libre
4            5   11  Guanajuato      1  Federal     Libre

  clasificacion_carretera          carretera  \
0                       D  Acambaro - Celaya
1                       D  Acambaro - Celaya
2                       A  Acambaro - Celaya
3                       A  Acambaro - Celaya
4                       A  Acambaro - Celaya

                                               tramo  km_inicial  ...    fs_e  \
0                      Acambaro-T. Izq. Inchamacuaro         0.0  ...  4967.0
1                   T. Izq. Inchamacuaro-Salvatierra        13.5  ...  1131.0
2               Salvatierra-T. Der. Rincon de Tamayo        33.0  ...  6578.0
3  T. Der. Rincon de Tamayo-X. C. Libramiento de ...        59.6  ...  7051.0
4                 X. C. Libramiento de Celaya-Celaya        69.7  ...  6900.0

   nivel_servicio  ejercicio  estado_ent  \
0               A       2024  Guanajuato
1               E       2024  Guanajuato
2               A       2024  Guanajuato
3               A       2024  Guanajuato
4               B       2024  Guanajuato

                                   _places   _carretera_places  \
0               [Acambaro, . Inchamacuaro]  [Acambaro, Celaya]
1            [. Inchamacuaro, Salvatierra]  [Acambaro, Celaya]
2  [Salvatierra, T. Der. Rincon de Tamayo]  [Acambaro, Celaya]
3       [T. Der. Rincon de Tamayo, Celaya]  [Acambaro, Celaya]
4                         [Celaya, Celaya]  [Acambaro, Celaya]

                                         _all_places  CVE_MUN match_score  \
0       [Acambaro, . Inchamacuaro, Acambaro, Celaya]    11002       100.0
1    [. Inchamacuaro, Salvatierra, Acambaro, Celaya]    11028       100.0
2  [Salvatierra, T. Der. Rincon de Tamayo, Acamba...    11028       100.0
3  [T. Der. Rincon de Tamayo, Celaya, Acambaro, C...    11007       100.0
4                 [Celaya, Celaya, Acambaro, Celaya]    11007       100.0

   longitud_sum
0        100.17
1         46.10
2         46.10
3         52.72
4         52.72

[5 rows x 32 columns]

In [ ]:
# take the average number of lanes per municipality
df["carriles_mean"] = df.groupby("CVE_MUN")["carriles"].transform("mean")
print(df.head())

   consecutivo  edo      estado  idred      red operacion  \
0            1   11  Guanajuato      1  Federal     Libre
1            2   11  Guanajuato      1  Federal     Libre
2            3   11  Guanajuato      1  Federal     Libre
3            4   11  Guanajuato      1  Federal     Libre
4            5   11  Guanajuato      1  Federal     Libre

  clasificacion_carretera          carretera  \
0                       D  Acambaro - Celaya
1                       D  Acambaro - Celaya
2                       A  Acambaro - Celaya
3                       A  Acambaro - Celaya
4                       A  Acambaro - Celaya

                                               tramo  km_inicial  ...  \
0                      Acambaro-T. Izq. Inchamacuaro         0.0  ...
1                   T. Izq. Inchamacuaro-Salvatierra        13.5  ...
2               Salvatierra-T. Der. Rincon de Tamayo        33.0  ...
3  T. Der. Rincon de Tamayo-X. C. Libramiento de ...        59.6  ...
4                 X. C. Libramiento de Celaya-Celaya        69.7  ...

   nivel_servicio  ejercicio  estado_ent  \
0               A       2024  Guanajuato
1               E       2024  Guanajuato
2               A       2024  Guanajuato
3               A       2024  Guanajuato
4               B       2024  Guanajuato

                                   _places   _carretera_places  \
0               [Acambaro, . Inchamacuaro]  [Acambaro, Celaya]
1            [. Inchamacuaro, Salvatierra]  [Acambaro, Celaya]
2  [Salvatierra, T. Der. Rincon de Tamayo]  [Acambaro, Celaya]
3       [T. Der. Rincon de Tamayo, Celaya]  [Acambaro, Celaya]
4                         [Celaya, Celaya]  [Acambaro, Celaya]

                                         _all_places CVE_MUN  match_score  \
0       [Acambaro, . Inchamacuaro, Acambaro, Celaya]   11002        100.0
1    [. Inchamacuaro, Salvatierra, Acambaro, Celaya]   11028        100.0
2  [Salvatierra, T. Der. Rincon de Tamayo, Acamba...   11028        100.0
3  [T. Der. Rincon de Tamayo, Celaya, Acambaro, C...   11007        100.0
4                 [Celaya, Celaya, Acambaro, Celaya]   11007        100.0

  longitud_sum  carriles_mean
0       100.17       3.250000
1        46.10       3.000000
2        46.10       3.000000
3        52.72       3.666667
4        52.72       3.666667

[5 rows x 33 columns]

In [181]:
# percentage with paid tolls
df["is_cuota"] = (df["operacion"] == "Cuota").astype(int)
df["share_cuota"] = df.groupby("CVE_MUN")["is_cuota"].transform("mean")

print(df.head())

   consecutivo  edo      estado  idred      red operacion  \
0            1   11  Guanajuato      1  Federal     Libre
1            2   11  Guanajuato      1  Federal     Libre
2            3   11  Guanajuato      1  Federal     Libre
3            4   11  Guanajuato      1  Federal     Libre
4            5   11  Guanajuato      1  Federal     Libre

  clasificacion_carretera          carretera  \
0                       D  Acambaro - Celaya
1                       D  Acambaro - Celaya
2                       A  Acambaro - Celaya
3                       A  Acambaro - Celaya
4                       A  Acambaro - Celaya

                                               tramo  km_inicial  ...  \
0                      Acambaro-T. Izq. Inchamacuaro         0.0  ...
1                   T. Izq. Inchamacuaro-Salvatierra        13.5  ...
2               Salvatierra-T. Der. Rincon de Tamayo        33.0  ...
3  T. Der. Rincon de Tamayo-X. C. Libramiento de ...        59.6  ...
4                 X. C. Libramiento de Celaya-Celaya        69.7  ...

   estado_ent                                  _places   _carretera_places  \
0  Guanajuato               [Acambaro, . Inchamacuaro]  [Acambaro, Celaya]
1  Guanajuato            [. Inchamacuaro, Salvatierra]  [Acambaro, Celaya]
2  Guanajuato  [Salvatierra, T. Der. Rincon de Tamayo]  [Acambaro, Celaya]
3  Guanajuato       [T. Der. Rincon de Tamayo, Celaya]  [Acambaro, Celaya]
4  Guanajuato                         [Celaya, Celaya]  [Acambaro, Celaya]

                                         _all_places  CVE_MUN  match_score  \
0       [Acambaro, . Inchamacuaro, Acambaro, Celaya]    11002        100.0
1    [. Inchamacuaro, Salvatierra, Acambaro, Celaya]    11028        100.0
2  [Salvatierra, T. Der. Rincon de Tamayo, Acamba...    11028        100.0
3  [T. Der. Rincon de Tamayo, Celaya, Acambaro, C...    11007        100.0
4                 [Celaya, Celaya, Acambaro, Celaya]    11007        100.0

  longitud_sum  carriles_mean is_cuota  share_cuota
0       100.17       3.250000        0     0.250000
1        46.10       3.000000        0     0.000000
2        46.10       3.000000        0     0.000000
3        52.72       3.666667        0     0.333333
4        52.72       3.666667        0     0.333333

[5 rows x 35 columns]

In [182]:
final_df2 = df[['CVE_MUN', 'longitud_sum', 'carriles_mean', 'share_cuota']].rename(columns={'CVE_MUN': 'CVEGEO'})

final_df2 = final_df2.groupby("CVEGEO").first().reset_index()

print(final_df2.head())

print(len(final_df2))

  CVEGEO  longitud_sum  carriles_mean  share_cuota
0  01001        297.43       3.333333      0.02381
1  01002          9.00       2.000000      0.00000
2  01003         14.50       4.000000      0.00000
3  01004          6.30       4.000000      0.00000
4  01006          2.84       4.000000      0.00000
666

In [186]:
final_df2.to_csv("roads2.csv", index=False)