In [59]:
import pandas as pd

service = pd.read_csv("data/water/servicio_agua_red_publica_cngmd2023_csv/conjunto_de_datos/servagua_cngmd2023.csv")

# WATER SERVICE HERE

## Var names from diccionario_de_datos_servagua_cngmd2023.csv
- mnpio: municipality -- Identifier for each questionnaire, composed of the state code and the municipality or borough code
- ag_servi: water_service -- Whether public water network service was provided as of end of 2022
- pobl_prc: population_pct_covered -- Percentage of the municipal or territorial population with access to public water network service as of end of 2022
- no_sabe: unknown	-- Whether the percentage of the municipal population with access to public water network service is unknown

In [60]:
service.head()

   mnpio  ag_servi  pobl_prc  no_sabe
0   1001         1     99.00        0
1   1002         1     75.00        0
2   1003         1     97.85        0
3   1004         1     98.00        0
4   1005         1     98.00        0

In [61]:
service = service.rename(columns={'mnpio': 'CVEGEO'})

In [62]:
print(service.head())
print('-------')
print(service['CVEGEO'].nunique)

   CVEGEO  ag_servi  pobl_prc  no_sabe
0    1001         1     99.00        0
1    1002         1     75.00        0
2    1003         1     97.85        0
3    1004         1     98.00        0
4    1005         1     98.00        0
-------
<bound method IndexOpsMixin.nunique of 0        1001
1        1002
2        1003
3        1004
4        1005
        ...
2470    32054
2471    32055
2472    32056
2473    32057
2474    32058
Name: CVEGEO, Length: 2475, dtype: int64>

In [63]:
service = service.drop(columns = ['no_sabe'])

In [64]:
key = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")

print(key.columns.tolist())


key["CVEGEO"] = key["CVEGEO"].astype(str).str.zfill(5)
service["CVEGEO"] = service["CVEGEO"].astype(str).str.zfill(5)


service = key[["CVEGEO"]].merge(
    service,
    on="CVEGEO",
    how="left"
)

print(service.head())
print(service["CVEGEO"].nunique())

print(service.columns.tolist())

['CVEGEO', 'NOMGEO', 'homicidio_doloso_2025', 'robo_veh_violencia_2025', 'n_inseguro_popw']
  CVEGEO  ag_servi  pobl_prc
0  01005       1.0      98.0
1  01008       1.0      98.0
2  01001       1.0      99.0
3  01004       1.0      98.0
4  01011       1.0       0.0
2478
['CVEGEO', 'ag_servi', 'pobl_prc']

In [65]:
covariate_cols = ['ag_servi', 'pobl_prc']

for col in covariate_cols:
    service[f"no_{col}"] = service[col].isna().astype(int)
    service[col] = service[col].fillna(0)


ordered_cols = ["CVEGEO"]
for col in covariate_cols:
    ordered_cols += [col, f"no_{col}"]

service = service[ordered_cols]

In [66]:
print(service)

     CVEGEO  ag_servi  no_ag_servi  pobl_prc  no_pobl_prc
0     01005       1.0            0      98.0            0
1     01008       1.0            0      98.0            0
2     01001       1.0            0      99.0            0
3     01004       1.0            0      98.0            0
4     01011       1.0            0       0.0            0
...     ...       ...          ...       ...          ...
2473  32007       1.0            0      98.0            0
2474  32047       1.0            0      97.0            0
2475  32012       1.0            0      80.0            0
2476  32006       1.0            0      90.0            0
2477  32011       1.0            0      90.0            0

[2478 rows x 5 columns]

In [67]:
print(service['no_ag_servi'].nunique())
print(service['no_pobl_prc'].nunique())

2
2

In [68]:
service.to_csv("data/covariates/water-service.csv", index=False)

# WATER SUPPLIED


## Var names from diccionario_de_datos_admnlocs_cngmd2023.csv
- id_local: locality_id -- Locality record identifier
- id_aps: water_provider_id	-- Water provider identifier
- mnpio: municipality -- Identifier for each questionnaire, composed of the state code and the municipality or borough code
- localid: locality_code -- Locality code
- loc_delo: locality_name -- Locality name
- ag_dias: water_days_per_week -- Average number of days per week water was supplied to users during 2022
- ag_horas: water_hours_per_day -- Average number of hours per day water was supplied to users during 2022

In [69]:
water_supplied = pd.read_csv("data/water/servicio_agua_red_publica_cngmd2023_csv/conjunto_de_datos/admnlocs_cngmd2023.csv")
print(water_supplied)

       id_local  id_aps  mnpio          localid              loc_delo ag_dias  \
0          1676   50338  14010  NO ESPECIFICADO            SAN MIGUEL       3
1          2303   50338  14010  NO ESPECIFICADO               YOLOSTA       3
2          2826   50338  14010  NO ESPECIFICADO               TELCOME       3
3          3253   50338  14010  NO ESPECIFICADO              VARILLAS       3
4          3625   50338  14010  NO ESPECIFICADO          PUEBLO NUEVO       3
...         ...     ...    ...              ...                   ...     ...
10665     24133   52693  15091               29  SANTA MARÍA CALIACAC     NSS
10666     24134   52670  15091                1            TEOLOYUCAN     NSS
10667     24135   52714  15091                1            TEOLOYUCAN     NSS
10668     24136   52687  15091                1            TEOLOYUCAN     NSS
10669     24137   52685  15091               10           SAN BARTOLO     NSS

      ag_horas
0            2
1            2
2            2
3            2
4            2
...        ...
10665      NSS
10666      NSS
10667      NSS
10668      NSS
10669      NSS

[10670 rows x 7 columns]

In [70]:
water_supplied

,id_local,id_aps,mnpio,localid,loc_delo,ag_dias,ag_horas
0,1676,50338,14010,NO ESPECIFICADO,SAN MIGUEL,3,2
1,2303,50338,14010,NO ESPECIFICADO,YOLOSTA,3,2
2,2826,50338,14010,NO ESPECIFICADO,TELCOME,3,2
3,3253,50338,14010,NO ESPECIFICADO,VARILLAS,3,2
4,3625,50338,14010,NO ESPECIFICADO,PUEBLO NUEVO,3,2
...,...,...,...,...,...,...,...
10665,24133,52693,15091,29,SANTA MARÍA CALIACAC,NSS,NSS
10666,24134,52670,15091,1,TEOLOYUCAN,NSS,NSS
10667,24135,52714,15091,1,TEOLOYUCAN,NSS,NSS
10668,24136,52687,15091,1,TEOLOYUCAN,NSS,NSS
10669,24137,52685,15091,10,SAN BARTOLO,NSS,NSS

In [71]:
water_supplied_collapsed = (
    water_supplied
    .assign(
        ag_dias=pd.to_numeric(water_supplied["ag_dias"], errors="coerce"),
        ag_horas=pd.to_numeric(water_supplied["ag_horas"], errors="coerce")
    )
    .groupby("mnpio")[["ag_dias", "ag_horas"]]
    .mean() # THIS IS AN UNWEIGHTED MEAN TO COLLAPSE TO THE MUNICIPALITY LEVEL. LOCALITY SIZES MAY DIFFERE WITHIN THE MUNICIPALITY WHICH IS A DRAWBACK OF THIS DATA. NO POPULATION COUNT FOR LOCALITY IN THIS FILE
    .reset_index()
    .rename(columns={"mnpio": "CVEGEO"})
)

water_supplied_collapsed["CVEGEO"] = water_supplied_collapsed["CVEGEO"].astype(str).str.zfill(5)

In [72]:
print(water_supplied_collapsed)

    CVEGEO  ag_dias   ag_horas
0    01003     5.90   8.466667
1    01004     6.25  12.583333
2    02002     7.00  24.000000
3    02006     7.00  13.000000
4    02007     7.00  24.000000
..     ...      ...        ...
919  32053     4.00  24.000000
920  32054     7.00  24.000000
921  32056     6.00  13.888889
922  32057     7.00  24.000000
923  32058     7.00  13.000000

[924 rows x 3 columns]

In [73]:
key = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")

print(key.columns.tolist())


key["CVEGEO"] = key["CVEGEO"].astype(str).str.zfill(5)
water_supplied_collapsed["CVEGEO"] = water_supplied_collapsed["CVEGEO"].astype(str).str.zfill(5)


water_supplied_collapsed = key[["CVEGEO"]].merge(
    water_supplied_collapsed,
    on="CVEGEO",
    how="left"
)

print(water_supplied_collapsed.head())
print(water_supplied_collapsed["CVEGEO"].nunique())

print(water_supplied_collapsed.columns.tolist())

['CVEGEO', 'NOMGEO', 'homicidio_doloso_2025', 'robo_veh_violencia_2025', 'n_inseguro_popw']
  CVEGEO  ag_dias   ag_horas
0  01005      NaN        NaN
1  01008      NaN        NaN
2  01001      NaN        NaN
3  01004     6.25  12.583333
4  01011      NaN        NaN
2478
['CVEGEO', 'ag_dias', 'ag_horas']

In [74]:
# zero insertion 

covariate_cols = ['ag_dias', 'ag_horas']

for col in covariate_cols:
    water_supplied_collapsed[f"no_{col}"] = water_supplied_collapsed[col].isna().astype(int)
    water_supplied_collapsed[col] = water_supplied_collapsed[col].fillna(0)


ordered_cols = ["CVEGEO"]
for col in covariate_cols:
    ordered_cols += [col, f"no_{col}"]

water_supplied_collapsed = water_supplied_collapsed[ordered_cols]

In [75]:
print(water_supplied_collapsed)

     CVEGEO   ag_dias  no_ag_dias   ag_horas  no_ag_horas
0     01005  0.000000           1   0.000000            1
1     01008  0.000000           1   0.000000            1
2     01001  0.000000           1   0.000000            1
3     01004  6.250000           0  12.583333            0
4     01011  0.000000           1   0.000000            1
...     ...       ...         ...        ...          ...
2473  32007  6.500000           0   6.250000            0
2474  32047  7.000000           0  12.000000            0
2475  32012  3.800000           0   3.600000            0
2476  32006  4.666667           0  18.000000            0
2477  32011  6.400000           0   7.600000            0

[2478 rows x 5 columns]

In [76]:
print(water_supplied_collapsed['no_ag_dias'].nunique())
print(water_supplied_collapsed['no_ag_horas'].nunique())

2
2

In [77]:
water_supplied_collapsed.to_csv("data/covariates/water-supplied-times.csv", index=False)

# DRAINAGE 

## Var names from diccionario_de_datos_servdren_cngmd2023.csv

- mnpio: municipality -- Municipality ID code
- serv_dre: drainage_service -- Whether drainage and sewage network service was provided as of end of 2022
- dren_cab: drainage_municipal_seat	-- Percentage of the municipal or territorial population with access to public drainage and sewage network service as of end of 2022
- no_saben: unknown	-- Whether the percentage of the municipal population with access to drainage and sewage service is unknown
- dren_plu: stormwater_drainage --	Whether the municipality had a stormwater drainage network separate from the sanitary sewer network
- prop_plu: stormwater_owned -- Primary purpose of the stormwater drainage network
- pr_plu_e: stormwater_spec	-- Specification of another purpose of the stormwater drainage network
- dren_ext: network_length_km -- Length of the stormwater drainage network in kilometers
- ext_reha: network_rehabilitated_km --	Length of the stormwater drainage network that was rehabilitated, in kilometers
- tot_conx: total_connections --Total number of connections covered by the drainage and sewage service
- con_cabe: connections_municipal_seat -- Number of connections in the municipal seat covered by the drainage and sewage service
- conx_loc: connections_localities -- Number of connections in the remaining localities of the municipality covered by the drainage and sewage service
- prest_nu: new_service_providers -- Number of drainage and sewage service providers or operators active in the municipality

In [78]:
drainage = pd.read_csv("data/water/drenaje_y_alcantarillado_cngmd2023_csv/conjunto_de_datos/servdren_cngmd2023.csv")

In [79]:
print(drainage)
print(drainage['mnpio'].nunique)

      mnpio  serv_dre  dren_cab  no_saben  dren_plu  prop_plu pr_plu_e  \
0     24047         2       NaN       NaN         0         0      NaN
1     16050         1       NaN       1.0         1         1      NaN
2     30092         1       NaN       1.0         1         2      NaN
3      2002         1      85.0       NaN         1         1      NaN
4      6003         1      91.3       NaN         1         1      NaN
...     ...       ...       ...       ...       ...       ...      ...
2470  13051         1      60.0       NaN         1         2      NaN
2471  21064         1      23.0       NaN         1         1      NaN
2472  22011         1      90.0       NaN         1         1      NaN
2473  30117         1      80.0       NaN         1         1      NaN
2474  30156         1      70.0       NaN         1         1      NaN

     dren_ext ext_reha tot_conx con_cabe conx_loc  prest_nu
0         NaN      NaN      NaN      NaN      NaN       NaN
1          20        5    15946    15659      287       1.0
2         1.2      0.3     4400     3200     1200       1.0
3      1030.1      1.7   314716   301269    13447       1.0
4         3.6     0.15     6381     6171      210       1.0
...       ...      ...      ...      ...      ...       ...
2470      NSS      NSS      NSS      NSS      NSS       1.0
2471      NSS      NSS      NSS      NSS      NSS       1.0
2472      NSS      NSS      NSS      NSS      NSS       1.0
2473      NSS      NSS      NSS      NSS      NSS       1.0
2474      NSS      NSS      NSS      NSS      NSS       1.0

[2475 rows x 13 columns]
<bound method IndexOpsMixin.nunique of 0       24047
1       16050
2       30092
3        2002
4        6003
        ...
2470    13051
2471    21064
2472    22011
2473    30117
2474    30156
Name: mnpio, Length: 2475, dtype: int64>

In [80]:
drainage = drainage.drop(columns = ['no_saben', 'prop_plu', 'pr_plu_e', 'dren_ext', 'ext_reha', 'con_cabe', 'conx_loc'])

In [81]:
print(drainage.head())

   mnpio  serv_dre  dren_cab  dren_plu tot_conx  prest_nu
0  24047         2       NaN         0      NaN       NaN
1  16050         1       NaN         1    15946       1.0
2  30092         1       NaN         1     4400       1.0
3   2002         1      85.0         1   314716       1.0
4   6003         1      91.3         1     6381       1.0

In [82]:
key = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")

print(key.columns.tolist())


drainage = drainage.rename(columns={'mnpio': 'CVEGEO'})

key["CVEGEO"] = key["CVEGEO"].astype(str).str.zfill(5)
drainage["CVEGEO"] = drainage["CVEGEO"].astype(str).str.zfill(5)


drainage = key[["CVEGEO"]].merge(
    drainage,
    on="CVEGEO",
    how="left"
)

print(drainage.head())
print(drainage["CVEGEO"].nunique())

print(drainage.columns.tolist())

['CVEGEO', 'NOMGEO', 'homicidio_doloso_2025', 'robo_veh_violencia_2025', 'n_inseguro_popw']
  CVEGEO  serv_dre  dren_cab  dren_plu tot_conx  prest_nu
0  01005       1.0     96.00       1.0    37015       1.0
1  01008       1.0     95.00       2.0     2752       1.0
2  01001       1.0     98.35       2.0   347981       1.0
3  01004       1.0     98.00       2.0     4670       1.0
4  01011       1.0       NaN       1.0    18820       1.0
2478
['CVEGEO', 'serv_dre', 'dren_cab', 'dren_plu', 'tot_conx', 'prest_nu']

In [83]:
covariate_cols = ['serv_dre', 'dren_cab', 'dren_plu', 'tot_conx', 'prest_nu']

for col in covariate_cols:
    drainage[f"no_{col}"] = drainage[col].isna().astype(int)
    drainage[col] = drainage[col].fillna(0)


ordered_cols = ["CVEGEO"]
for col in covariate_cols:
    ordered_cols += [col, f"no_{col}"]

drainage = drainage[ordered_cols]

In [84]:
print(drainage)

     CVEGEO  serv_dre  no_serv_dre  dren_cab  no_dren_cab  dren_plu  \
0     01005       1.0            0     96.00            0       1.0
1     01008       1.0            0     95.00            0       2.0
2     01001       1.0            0     98.35            0       2.0
3     01004       1.0            0     98.00            0       2.0
4     01011       1.0            0      0.00            1       1.0
...     ...       ...          ...       ...          ...       ...
2473  32007       1.0            0     98.00            0       2.0
2474  32047       1.0            0     97.00            0       2.0
2475  32012       1.0            0     31.00            0       2.0
2476  32006       1.0            0    100.00            0       2.0
2477  32011       1.0            0     90.00            0       2.0

      no_dren_plu tot_conx  no_tot_conx  prest_nu  no_prest_nu
0               0    37015            0       1.0            0
1               0     2752            0       1.0            0
2               0   347981            0       1.0            0
3               0     4670            0       1.0            0
4               0    18820            0       1.0            0
...           ...      ...          ...       ...          ...
2473            0     3068            0       1.0            0
2474            0     2277            0       1.0            0
2475            0      656            0       1.0            0
2476            0     2200            0       1.0            0
2477            0     1736            0       1.0            0

[2478 rows x 11 columns]

In [85]:
print(drainage['no_serv_dre'].nunique())
print(drainage['no_dren_cab'].nunique())
print(drainage['no_dren_plu'].nunique())
print(drainage['no_tot_conx'].nunique())
print(drainage['no_prest_nu'].nunique())

2
2
2
2
2

In [86]:
drainage.to_csv("data/covariates/drainage.csv", index=False)

# COMBINING ALL DATASETS TOGETHER

In [87]:
water_drainage_merged = (
    service
    .merge(water_supplied_collapsed, on="CVEGEO", how="outer")
    .merge(drainage, on="CVEGEO", how="outer")
)

In [88]:
print(water_drainage_merged)

     CVEGEO  ag_servi  no_ag_servi  pobl_prc  no_pobl_prc  ag_dias  \
0     01001       1.0            0     99.00            0     0.00
1     01002       1.0            0     75.00            0     0.00
2     01003       1.0            0     97.85            0     5.90
3     01004       1.0            0     98.00            0     6.25
4     01005       1.0            0     98.00            0     0.00
...     ...       ...          ...       ...          ...      ...
2473  32054       1.0            0     97.00            0     7.00
2474  32055       1.0            0     43.22            0     0.00
2475  32056       1.0            0     99.20            0     6.00
2476  32057       1.0            0     90.00            0     7.00
2477  32058       1.0            0     95.00            0     7.00

      no_ag_dias   ag_horas  no_ag_horas  serv_dre  no_serv_dre  dren_cab  \
0              1   0.000000            1       1.0            0     98.35
1              1   0.000000            1       1.0            0     85.00
2              0   8.466667            0       1.0            0      0.00
3              0  12.583333            0       1.0            0     98.00
4              1   0.000000            1       1.0            0     96.00
...          ...        ...          ...       ...          ...       ...
2473           0  24.000000            0       1.0            0     97.00
2474           1   0.000000            1       1.0            0     80.00
2475           0  13.888889            0       1.0            0     85.12
2476           0  24.000000            0       1.0            0     90.00
2477           0  13.000000            0       1.0            0     95.00

      no_dren_cab  dren_plu  no_dren_plu tot_conx  no_tot_conx  prest_nu  \
0               0       2.0            0   347981            0       1.0
1               0       2.0            0    13800            0       1.0
2               1       2.0            0    19790            0       1.0
3               0       2.0            0     4670            0       1.0
4               0       1.0            0    37015            0       1.0
...           ...       ...          ...      ...          ...       ...
2473            0       2.0            0     1743            0       1.0
2474            0       2.0            0     5527            0       1.0
2475            0       2.0            0   123023            0       1.0
2476            0       2.0            0     4320            0       1.0
2477            0       2.0            0     1270            0       1.0

      no_prest_nu
0               0
1               0
2               0
3               0
4               0
...           ...
2473            0
2474            0
2475            0
2476            0
2477            0

[2478 rows x 19 columns]

In [89]:
print(water_drainage_merged['CVEGEO'].nunique)

<bound method IndexOpsMixin.nunique of 0       01001
1       01002
2       01003
3       01004
4       01005
        ...
2473    32054
2474    32055
2475    32056
2476    32057
2477    32058
Name: CVEGEO, Length: 2478, dtype: object>