In [ ]:
import pandas as pd

service = pd.read_csv("data/water/servicio_agua_red_publica_cngmd2023_csv/conjunto_de_datos/servagua_cngmd2023.csv")
water_info = pd.read_csv("data/water/servicio_agua_red_publica_cngmd2023_csv/conjunto_de_datos/admnapsa_cngmd2023.csv")

# WATER SERVICE HERE

## Var names
- mnpio: municipality -- Municipality ID code
- ag_servi: water_service -- Whether the municipality has public water network service (binary)
- pobl_prc: population_pct_covered -- Percentage of population with access to public water network
- no_sabe: unknown	-- Whether coverage percentage is unknown

In [2]:
service.head()

   mnpio  ag_servi  pobl_prc  no_sabe
0   1001         1     99.00        0
1   1002         1     75.00        0
2   1003         1     97.85        0
3   1004         1     98.00        0
4   1005         1     98.00        0

In [3]:
service = service.rename(columns={'mnpio': 'CVEGEO'})

In [6]:
print(service.head())
print('-------')
print(service['CVEGEO'].nunique)

   CVEGEO  ag_servi  pobl_prc  no_sabe
0    1001         1     99.00        0
1    1002         1     75.00        0
2    1003         1     97.85        0
3    1004         1     98.00        0
4    1005         1     98.00        0
-------
<bound method IndexOpsMixin.nunique of 0        1001
1        1002
2        1003
3        1004
4        1005
        ...
2470    32054
2471    32055
2472    32056
2473    32057
2474    32058
Name: CVEGEO, Length: 2475, dtype: int64>

In [11]:
key = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")

print(key.columns.tolist())


key["CVEGEO"] = key["CVEGEO"].astype(str).str.zfill(5)
service["CVEGEO"] = service["CVEGEO"].astype(str).str.zfill(5)


service = key[["CVEGEO"]].merge(
    service,
    on="CVEGEO",
    how="left"
)

print(service.head())
print(service["CVEGEO"].nunique())

print(service.columns.tolist())

['CVEGEO', 'NOMGEO', 'homicidio_doloso_2025', 'robo_veh_violencia_2025', 'n_inseguro_popw']
  CVEGEO  ag_servi  pobl_prc  no_sabe
0  01005       1.0      98.0      0.0
1  01008       1.0      98.0      0.0
2  01001       1.0      99.0      0.0
3  01004       1.0      98.0      0.0
4  01011       1.0       0.0      1.0
2478
['CVEGEO', 'ag_servi', 'pobl_prc', 'no_sabe']

In [12]:
covariate_cols = ['ag_servi', 'pobl_prc', 'no_sabe']

for col in covariate_cols:
    service[f"no_{col}"] = service[col].isna().astype(int)
    service[col] = service[col].fillna(0)


ordered_cols = ["CVEGEO"]
for col in covariate_cols:
    ordered_cols += [col, f"no_{col}"]

service = service[ordered_cols]

In [18]:
print(service)

     CVEGEO  ag_servi  no_ag_servi  pobl_prc  no_pobl_prc  no_sabe  no_no_sabe
0     01005       1.0            0      98.0            0      0.0           0
1     01008       1.0            0      98.0            0      0.0           0
2     01001       1.0            0      99.0            0      0.0           0
3     01004       1.0            0      98.0            0      0.0           0
4     01011       1.0            0       0.0            0      1.0           0
...     ...       ...          ...       ...          ...      ...         ...
2473  32007       1.0            0      98.0            0      0.0           0
2474  32047       1.0            0      97.0            0      0.0           0
2475  32012       1.0            0      80.0            0      0.0           0
2476  32006       1.0            0      90.0            0      0.0           0
2477  32011       1.0            0      90.0            0      0.0           0

[2478 rows x 7 columns]

In [19]:
print(service['no_ag_servi'].nunique())
print(service['no_pobl_prc'].nunique())
print(service['no_no_sabe'].nunique())

2
2
2

In [20]:
service.to_csv("data/covariates/water-service.csv", index=False)

# WATER SUPPLIED


## Var names
- id_local: locality_id -- Unique identifier for each locality record
- id_aps: water_provider_id	-- ID linking to the provider in admnapsa
- mnpio: municipality -- Municipality ID code
- localid: locality_code -- Official locality code
- loc_delo: locality_name -- Name of the locality served
- ag_dias: water_days_per_week -- Average days per week water was supplied to users
- ag_horas: water_hours_per_day -- Average hours per day water was supplied to users

In [28]:
water_supplied = pd.read_csv("data/water/servicio_agua_red_publica_cngmd2023_csv/conjunto_de_datos/admnlocs_cngmd2023.csv")
print(water_supplied)

       id_local  id_aps  mnpio          localid              loc_delo ag_dias  \
0          1676   50338  14010  NO ESPECIFICADO            SAN MIGUEL       3
1          2303   50338  14010  NO ESPECIFICADO               YOLOSTA       3
2          2826   50338  14010  NO ESPECIFICADO               TELCOME       3
3          3253   50338  14010  NO ESPECIFICADO              VARILLAS       3
4          3625   50338  14010  NO ESPECIFICADO          PUEBLO NUEVO       3
...         ...     ...    ...              ...                   ...     ...
10665     24133   52693  15091               29  SANTA MARÍA CALIACAC     NSS
10666     24134   52670  15091                1            TEOLOYUCAN     NSS
10667     24135   52714  15091                1            TEOLOYUCAN     NSS
10668     24136   52687  15091                1            TEOLOYUCAN     NSS
10669     24137   52685  15091               10           SAN BARTOLO     NSS

      ag_horas
0            2
1            2
2            2
3            2
4            2
...        ...
10665      NSS
10666      NSS
10667      NSS
10668      NSS
10669      NSS

[10670 rows x 7 columns]

In [29]:
water_supplied

,id_local,id_aps,mnpio,localid,loc_delo,ag_dias,ag_horas
0,1676,50338,14010,NO ESPECIFICADO,SAN MIGUEL,3,2
1,2303,50338,14010,NO ESPECIFICADO,YOLOSTA,3,2
2,2826,50338,14010,NO ESPECIFICADO,TELCOME,3,2
3,3253,50338,14010,NO ESPECIFICADO,VARILLAS,3,2
4,3625,50338,14010,NO ESPECIFICADO,PUEBLO NUEVO,3,2
...,...,...,...,...,...,...,...
10665,24133,52693,15091,29,SANTA MARÍA CALIACAC,NSS,NSS
10666,24134,52670,15091,1,TEOLOYUCAN,NSS,NSS
10667,24135,52714,15091,1,TEOLOYUCAN,NSS,NSS
10668,24136,52687,15091,1,TEOLOYUCAN,NSS,NSS
10669,24137,52685,15091,10,SAN BARTOLO,NSS,NSS

In [35]:
water_supplied_collapsed = (
    water_supplied
    .assign(
        ag_dias=pd.to_numeric(water_supplied["ag_dias"], errors="coerce"),
        ag_horas=pd.to_numeric(water_supplied["ag_horas"], errors="coerce")
    )
    .groupby("mnpio")[["ag_dias", "ag_horas"]]
    .mean() # THIS IS AN UNWEIGHTED MEAN TO COLLAPSE TO THE MUNICIPALITY LEVEL. LOCALITY SIZES MAY DIFFERE WITHIN THE MUNICIPALITY WHICH IS A DRAWBACK OF THIS DATA. NO POPULATION COUNT FOR LOCALITY IN THIS FILE
    .reset_index()
    .rename(columns={"mnpio": "CVEGEO"})
)

water_supplied_collapsed["CVEGEO"] = locs_collapsed["CVEGEO"].astype(str).str.zfill(5)

In [36]:
print(water_supplied_collapsed)

    CVEGEO  ag_dias   ag_horas
0    01003     5.90   8.466667
1    01004     6.25  12.583333
2    02002     7.00  24.000000
3    02006     7.00  13.000000
4    02007     7.00  24.000000
..     ...      ...        ...
919  32053     4.00  24.000000
920  32054     7.00  24.000000
921  32056     6.00  13.888889
922  32057     7.00  24.000000
923  32058     7.00  13.000000

[924 rows x 3 columns]

In [37]:
key = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")

print(key.columns.tolist())


key["CVEGEO"] = key["CVEGEO"].astype(str).str.zfill(5)
water_supplied_collapsed["CVEGEO"] = water_supplied_collapsed["CVEGEO"].astype(str).str.zfill(5)


water_supplied_collapsed = key[["CVEGEO"]].merge(
    water_supplied_collapsed,
    on="CVEGEO",
    how="left"
)

print(water_supplied_collapsed.head())
print(water_supplied_collapsed["CVEGEO"].nunique())

print(water_supplied_collapsed.columns.tolist())

['CVEGEO', 'NOMGEO', 'homicidio_doloso_2025', 'robo_veh_violencia_2025', 'n_inseguro_popw']
  CVEGEO  ag_dias   ag_horas
0  01005      NaN        NaN
1  01008      NaN        NaN
2  01001      NaN        NaN
3  01004     6.25  12.583333
4  01011      NaN        NaN
2478
['CVEGEO', 'ag_dias', 'ag_horas']

In [38]:
covariate_cols = ['ag_dias', 'ag_horas']

for col in covariate_cols:
    water_supplied_collapsed[f"no_{col}"] = water_supplied_collapsed[col].isna().astype(int)
    water_supplied_collapsed[col] = water_supplied_collapsed[col].fillna(0)


ordered_cols = ["CVEGEO"]
for col in covariate_cols:
    ordered_cols += [col, f"no_{col}"]

water_supplied_collapsed = water_supplied_collapsed[ordered_cols]

In [39]:
print(water_supplied_collapsed)

     CVEGEO   ag_dias  no_ag_dias   ag_horas  no_ag_horas
0     01005  0.000000           1   0.000000            1
1     01008  0.000000           1   0.000000            1
2     01001  0.000000           1   0.000000            1
3     01004  6.250000           0  12.583333            0
4     01011  0.000000           1   0.000000            1
...     ...       ...         ...        ...          ...
2473  32007  6.500000           0   6.250000            0
2474  32047  7.000000           0  12.000000            0
2475  32012  3.800000           0   3.600000            0
2476  32006  4.666667           0  18.000000            0
2477  32011  6.400000           0   7.600000            0

[2478 rows x 5 columns]

In [40]:
print(water_supplied_collapsed['no_ag_dias'].nunique())
print(water_supplied_collapsed['no_ag_horas'].nunique())

2
2

In [41]:
water_supplied_collapsed.to_csv("data/covariates/water-supplied-times.csv", index=False)