# Merging part 1

- traffic (roads1 csv)
- ice
- mexico census infrastructure data
- schools infrastructure data

In [12]:
import pandas as pd

df = pd.read_csv("data/covariates/ethan_final_key_df_head.csv")
traffic = pd.read_csv("data/covariates/roads1.csv")
ice = pd.read_csv("data/covariates/ice_covariates.csv")
census = pd.read_csv("data/covariates/mexico_census_infrastructure_data.csv")
schools = pd.read_csv("data/covariates/school_infrastructure_covariates.csv")

In [13]:
df.head()

,CVEGEO,NOMGEO,homicidio_doloso_2025,robo_veh_violencia_2025,n_inseguro_popw
0,1005,Jesús María,15.0,16.0,48465.88493
1,1008,San José de Gracia,1.0,1.0,NaN
2,1001,Aguascalientes,41.0,47.0,264703.23100
3,1004,Cosío,2.0,7.0,NaN
4,1011,San Francisco de los Romo,5.0,5.0,18028.05971

In [14]:
traffic.head()

,municipio,CVEGEO,tdpa_avg,no_tdpa_avg,punto_generador_count,no_punto_generador_count,m_avg,no_m_avg,a_avg,no_a_avg,...,t3s2r4_avg,no_t3s2r4_avg,otros_avg,no_otros_avg,aa_avg,no_aa_avg,bb_avg,no_bb_avg,cc_avg,no_cc_avg
0,Aguascalientes,1001,11298.763489,0,30.0,0,2.917626,0,80.986960,0,...,1.057104,0,0.368615,0,83.904586,0,2.227788,0,13.867626,0
1,Asientos,1002,4616.674641,0,10.0,0,5.194737,0,80.874641,0,...,0.126794,0,0.233014,0,86.069378,0,1.878469,0,12.052153,0
2,Calvillo,1003,4997.627660,0,11.0,0,2.532979,0,88.263298,0,...,0.090957,0,0.110106,0,90.796277,0,0.742553,0,8.461170,0
3,Cosío,1004,6973.539568,0,3.0,0,3.200719,0,68.954676,0,...,3.424460,0,0.668345,0,72.155396,0,4.274101,0,23.570504,0
4,Jesús María,1005,11065.404598,0,16.0,0,2.894713,0,83.057011,0,...,0.579310,0,0.248046,0,85.951724,0,1.494253,0,12.554023,0

In [15]:
traffic = traffic.drop(columns=['municipio'])

In [16]:
ice.head()

,CVEGEO,NOMGEO,IM_2020,no_IM_2020,IE,no_IE,TCVCU,no_TCVCU,ICE,no_ICE
0,1005,Jesús María,59.011762,0,2.757816,0,10,0,15.172939,0
1,1008,San José de Gracia,57.527531,0,0.624208,0,30,0,12.413795,0
2,1001,Aguascalientes,60.318795,0,30.802086,0,2,0,43.710758,0
3,1004,Cosío,57.114030,0,0.318518,0,25,0,12.080517,0
4,1011,San Francisco de los Romo,58.552098,0,0.966893,0,13,0,13.220455,0

In [17]:
ice = ice.drop(columns = ['NOMGEO'])

In [18]:
census.head()

,CVEGEO,NOMGEO,VIVPAR_HAB,no_VIVPAR_HAB,POBTOT,no_POBTOT,pct_VPH_SINTIC,no_pct_VPH_SINTIC,pct_VPH_C_ELEC,no_pct_VPH_C_ELEC,pct_VPH_AGUADV,no_pct_VPH_AGUADV,pct_VPH_PISODT,no_pct_VPH_PISODT,pct_VPH_PISOTI,no_pct_VPH_PISOTI,pct_VPH_1CUART,no_pct_VPH_1CUART
0,1005,Jesús María,32267,0,129929,0,0.004587,0,1.022004,0,1.017913,0,1.014008,0,0.012737,0,0.024576,0
1,1008,San José de Gracia,2377,0,9552,0,0.015145,0,0.986538,0,0.981489,0,0.990324,0,0.010097,0,0.028187,0
2,1001,Aguascalientes,257719,0,948990,0,0.002836,0,1.031298,0,1.029152,0,1.026940,0,0.005937,0,0.012358,0
3,1004,Cosío,3933,0,17000,0,0.012713,0,0.993135,0,0.991609,0,0.989321,0,0.010170,0,0.030511,0
4,1011,San Francisco de los Romo,16194,0,61997,0,0.005866,0,1.004137,0,1.003335,0,1.001482,0,0.007225,0,0.015314,0

In [19]:
census = census.drop(columns = ['NOMGEO'])

In [20]:
schools.head()

,CVEGEO,NOMGEO,n_schools_avg,no_n_schools_avg,pct_con_bebederos,no_pct_con_bebederos,pct_con_proteccion_civil,no_pct_con_proteccion_civil,pct_con_cancha,no_pct_con_cancha,avg_anio_creacion,no_avg_anio_creacion
0,1005,JESUS MARIA,10.666667,0,0.180995,0,0.161388,0,0.567873,0,1980.245852,0
1,1008,SAN JOSE DE GRACIA,6.000000,0,0.500000,0,0.666667,0,0.333333,0,1987.333333,0
2,1001,AGUASCALIENTES,25.333333,0,0.559261,0,0.473644,0,0.717439,0,1978.161775,0
3,1004,COSIO,5.500000,0,0.732143,0,0.196429,0,0.714286,0,1968.678571,0
4,1011,SAN FRANCISCO DE LOS ROMO,6.000000,0,0.312500,0,0.125000,0,0.687500,0,1983.687500,0

In [21]:
schools = schools.drop(columns = ['NOMGEO'])

In [22]:
print(df["CVEGEO"].nunique())
print(traffic["CVEGEO"].nunique())
print(ice["CVEGEO"].nunique())
print(census["CVEGEO"].nunique())
print(schools["CVEGEO"].nunique())

2478
2486
2478
2478
2478

In [23]:
anti_join1 = df[~df["CVEGEO"].isin(traffic["CVEGEO"])]

print(anti_join1["CVEGEO"].nunique())

anti_join2 = traffic[~traffic["CVEGEO"].isin(df["CVEGEO"])]

print(anti_join2["CVEGEO"].nunique())
print(anti_join2["CVEGEO"].unique())

print(anti_join2)

0
8
[ 9998 14998 20999 22998 26998 26999 30998 30999]
      CVEGEO  tdpa_avg  no_tdpa_avg  punto_generador_count  \
291     9998       0.0            1                    0.0
671    14998       0.0            1                    0.0
1587   20999       0.0            1                    0.0
1823   22998       0.0            1                    0.0
1986   26998       0.0            1                    0.0
1987   26999       0.0            1                    0.0
2320   30998       0.0            1                    0.0
2321   30999       0.0            1                    0.0

      no_punto_generador_count  m_avg  no_m_avg  a_avg  no_a_avg  b_avg  ...  \
291                          1    0.0         1    0.0         1    0.0  ...
671                          1    0.0         1    0.0         1    0.0  ...
1587                         1    0.0         1    0.0         1    0.0  ...
1823                         1    0.0         1    0.0         1    0.0  ...
1986                         1    0.0         1    0.0         1    0.0  ...
1987                         1    0.0         1    0.0         1    0.0  ...
2320                         1    0.0         1    0.0         1    0.0  ...
2321                         1    0.0         1    0.0         1    0.0  ...

      t3s2r4_avg  no_t3s2r4_avg  otros_avg  no_otros_avg  aa_avg  no_aa_avg  \
291          0.0              1        0.0             1     0.0          1
671          0.0              1        0.0             1     0.0          1
1587         0.0              1        0.0             1     0.0          1
1823         0.0              1        0.0             1     0.0          1
1986         0.0              1        0.0             1     0.0          1
1987         0.0              1        0.0             1     0.0          1
2320         0.0              1        0.0             1     0.0          1
2321         0.0              1        0.0             1     0.0          1

      bb_avg  no_bb_avg  cc_avg  no_cc_avg
291      0.0          1     0.0          1
671      0.0          1     0.0          1
1587     0.0          1     0.0          1
1823     0.0          1     0.0          1
1986     0.0          1     0.0          1
1987     0.0          1     0.0          1
2320     0.0          1     0.0          1
2321     0.0          1     0.0          1

[8 rows x 29 columns]

In [24]:
codes_to_drop = [9998, 14998, 20999, 22998, 26998, 26999, 30998, 30999]
traffic = traffic[~traffic["CVEGEO"].isin(codes_to_drop)]

In [25]:
print(df["CVEGEO"].nunique())
print(traffic["CVEGEO"].nunique())
print(ice["CVEGEO"].nunique())
print(census["CVEGEO"].nunique())
print(schools["CVEGEO"].nunique())

2478
2478
2478
2478
2478

In [26]:
merged = df.merge(traffic, on="CVEGEO", how="outer") \
           .merge(ice, on="CVEGEO", how="outer") \
           .merge(census, on="CVEGEO", how="outer") \
           .merge(schools, on="CVEGEO", how="outer")

In [27]:
merged.head()

,CVEGEO,NOMGEO,homicidio_doloso_2025,robo_veh_violencia_2025,n_inseguro_popw,tdpa_avg,no_tdpa_avg,punto_generador_count,no_punto_generador_count,m_avg,...,n_schools_avg,no_n_schools_avg,pct_con_bebederos,no_pct_con_bebederos,pct_con_proteccion_civil,no_pct_con_proteccion_civil,pct_con_cancha,no_pct_con_cancha,avg_anio_creacion,no_avg_anio_creacion
0,1001,Aguascalientes,41.0,47.0,264703.23100,11298.763489,0,30.0,0,2.917626,...,25.333333,0,0.559261,0,0.473644,0,0.717439,0,1978.161775,0
1,1002,Asientos,3.0,10.0,20111.86968,4616.674641,0,10.0,0,5.194737,...,14.333333,0,0.219096,0,0.325661,0,0.510941,0,1975.178460,0
2,1003,Calvillo,0.0,2.0,14514.80605,4997.627660,0,11.0,0,2.532979,...,14.000000,0,0.164141,0,0.194444,0,0.618687,0,1986.751263,0
3,1004,Cosío,2.0,7.0,NaN,6973.539568,0,3.0,0,3.200719,...,5.500000,0,0.732143,0,0.196429,0,0.714286,0,1968.678571,0
4,1005,Jesús María,15.0,16.0,48465.88493,11065.404598,0,16.0,0,2.894713,...,10.666667,0,0.180995,0,0.161388,0,0.567873,0,1980.245852,0

In [28]:
merged.columns.tolist()

['CVEGEO',
 'NOMGEO',
 'homicidio_doloso_2025',
 'robo_veh_violencia_2025',
 'n_inseguro_popw',
 'tdpa_avg',
 'no_tdpa_avg',
 'punto_generador_count',
 'no_punto_generador_count',
 'm_avg',
 'no_m_avg',
 'a_avg',
 'no_a_avg',
 'b_avg',
 'no_b_avg',
 'c2_avg',
 'no_c2_avg',
 'c3_avg',
 'no_c3_avg',
 't3s2_avg',
 'no_t3s2_avg',
 't3s3_avg',
 'no_t3s3_avg',
 't3s2r4_avg',
 'no_t3s2r4_avg',
 'otros_avg',
 'no_otros_avg',
 'aa_avg',
 'no_aa_avg',
 'bb_avg',
 'no_bb_avg',
 'cc_avg',
 'no_cc_avg',
 'IM_2020',
 'no_IM_2020',
 'IE',
 'no_IE',
 'TCVCU',
 'no_TCVCU',
 'ICE',
 'no_ICE',
 'VIVPAR_HAB',
 'no_VIVPAR_HAB',
 'POBTOT',
 'no_POBTOT',
 'pct_VPH_SINTIC',
 'no_pct_VPH_SINTIC',
 'pct_VPH_C_ELEC',
 'no_pct_VPH_C_ELEC',
 'pct_VPH_AGUADV',
 'no_pct_VPH_AGUADV',
 'pct_VPH_PISODT',
 'no_pct_VPH_PISODT',
 'pct_VPH_PISOTI',
 'no_pct_VPH_PISOTI',
 'pct_VPH_1CUART',
 'no_pct_VPH_1CUART',
 'n_schools_avg',
 'no_n_schools_avg',
 'pct_con_bebederos',
 'no_pct_con_bebederos',
 'pct_con_proteccion_civil',
 'no_pct_con_proteccion_civil',
 'pct_con_cancha',
 'no_pct_con_cancha',
 'avg_anio_creacion',
 'no_avg_anio_creacion']

In [29]:
merged.to_csv("merged_covariates.csv", index=False)

# MERGED is the MERGED CSV UP TO HERE
# Merging part 2

- federal and parastatal real estate
- roads

In [30]:
import pandas as pd 

merged = pd.read_csv("merged_covariates.csv")
road_shape = pd.read_csv("data/covariates/municipality_road_summary.csv")
federal_palaces = pd.read_csv("data/covariates/Federal_and_Parastatal_Real_Estate_Assets_Final.csv")

In [31]:
print(road_shape.head())
print(road_shape['CVEGEO'].nunique())


road_shape["CVEGEO"] = road_shape["CVEGEO"].astype(str).str.zfill(5)
road_shape = road_shape.drop(columns = ['NOMGEO'])


print("-------------")
print(road_shape.head())

   CVEGEO          NOMGEO  km_carretera_fed  km_carretera_est  km_cuota  \
0    1001  Aguascalientes        137.033408        243.822890   2.10033
1    1002        Asientos         36.738584        130.400787   0.00000
2    1003        Calvillo         35.584418         79.664707   0.00000
3    1004           Cosío         23.869664         37.509974   0.00000
4    1005     Jesús María         67.897541         86.700740  25.36572

    km_camino  km_vereda  km_vialidad_urbana     km_total
0  459.437409   0.000000         1873.548644  3004.866873
1  201.726355   0.000000           30.652053   410.013174
2  394.006289   0.383861           56.450543   574.066726
3   68.372297   0.000000           43.043676   185.919289
4  222.798212   0.000000          310.238861   762.100377
2478
-------------
  CVEGEO  km_carretera_fed  km_carretera_est  km_cuota   km_camino  km_vereda  \
0  01001        137.033408        243.822890   2.10033  459.437409   0.000000
1  01002         36.738584        130.400787   0.00000  201.726355   0.000000
2  01003         35.584418         79.664707   0.00000  394.006289   0.383861
3  01004         23.869664         37.509974   0.00000   68.372297   0.000000
4  01005         67.897541         86.700740  25.36572  222.798212   0.000000

   km_vialidad_urbana     km_total
0         1873.548644  3004.866873
1           30.652053   410.013174
2           56.450543   574.066726
3           43.043676   185.919289
4          310.238861   762.100377

In [32]:
print(federal_palaces.head())
print(federal_palaces['CVEGEO'].nunique())

federal_palaces["CVEGEO"] = federal_palaces["CVEGEO"].astype(str).str.zfill(5)
federal_palaces = federal_palaces.drop(columns = ['NOMGEO'])


print('-----------')
print(federal_palaces.head())

   CVEGEO                     NOMGEO  n_federal_offices  no_n_federal_offices
0    1005                JESUS MARIA                  9                     0
1    1008         SAN JOSE DE GRACIA                  8                     0
2    1001             AGUASCALIENTES                133                     0
3    1004                      COSIO                  6                     0
4    1011  SAN FRANCISCO DE LOS ROMO                  3                     0
2478
-----------
  CVEGEO  n_federal_offices  no_n_federal_offices
0  01005                  9                     0
1  01008                  8                     0
2  01001                133                     0
3  01004                  6                     0
4  01011                  3                     0

In [33]:
print(merged.head())

   CVEGEO          NOMGEO  homicidio_doloso_2025  robo_veh_violencia_2025  \
0    1001  Aguascalientes                   41.0                     47.0
1    1002        Asientos                    3.0                     10.0
2    1003        Calvillo                    0.0                      2.0
3    1004           Cosío                    2.0                      7.0
4    1005     Jesús María                   15.0                     16.0

   n_inseguro_popw      tdpa_avg  no_tdpa_avg  punto_generador_count  \
0     264703.23100  11298.763489            0                   30.0
1      20111.86968   4616.674641            0                   10.0
2      14514.80605   4997.627660            0                   11.0
3              NaN   6973.539568            0                    3.0
4      48465.88493  11065.404598            0                   16.0

   no_punto_generador_count     m_avg  ...  n_schools_avg  no_n_schools_avg  \
0                         0  2.917626  ...      25.333333                 0
1                         0  5.194737  ...      14.333333                 0
2                         0  2.532979  ...      14.000000                 0
3                         0  3.200719  ...       5.500000                 0
4                         0  2.894713  ...      10.666667                 0

   pct_con_bebederos  no_pct_con_bebederos  pct_con_proteccion_civil  \
0           0.559261                     0                  0.473644
1           0.219096                     0                  0.325661
2           0.164141                     0                  0.194444
3           0.732143                     0                  0.196429
4           0.180995                     0                  0.161388

   no_pct_con_proteccion_civil  pct_con_cancha  no_pct_con_cancha  \
0                            0        0.717439                  0
1                            0        0.510941                  0
2                            0        0.618687                  0
3                            0        0.714286                  0
4                            0        0.567873                  0

   avg_anio_creacion  no_avg_anio_creacion
0        1978.161775                     0
1        1975.178460                     0
2        1986.751263                     0
3        1968.678571                     0
4        1980.245852                     0

[5 rows x 67 columns]

In [34]:
merged['CVEGEO'] = merged['CVEGEO'].astype(str).str.zfill(5)


merged = merged.merge(road_shape, on="CVEGEO", how="outer") \
           .merge(federal_palaces, on="CVEGEO", how="outer")

In [35]:
print(merged.head())

  CVEGEO          NOMGEO  homicidio_doloso_2025  robo_veh_violencia_2025  \
0  01001  Aguascalientes                   41.0                     47.0
1  01002        Asientos                    3.0                     10.0
2  01003        Calvillo                    0.0                      2.0
3  01004           Cosío                    2.0                      7.0
4  01005     Jesús María                   15.0                     16.0

   n_inseguro_popw      tdpa_avg  no_tdpa_avg  punto_generador_count  \
0     264703.23100  11298.763489            0                   30.0
1      20111.86968   4616.674641            0                   10.0
2      14514.80605   4997.627660            0                   11.0
3              NaN   6973.539568            0                    3.0
4      48465.88493  11065.404598            0                   16.0

   no_punto_generador_count     m_avg  ...  no_avg_anio_creacion  \
0                         0  2.917626  ...                     0
1                         0  5.194737  ...                     0
2                         0  2.532979  ...                     0
3                         0  3.200719  ...                     0
4                         0  2.894713  ...                     0

   km_carretera_fed  km_carretera_est  km_cuota   km_camino  km_vereda  \
0        137.033408        243.822890   2.10033  459.437409   0.000000
1         36.738584        130.400787   0.00000  201.726355   0.000000
2         35.584418         79.664707   0.00000  394.006289   0.383861
3         23.869664         37.509974   0.00000   68.372297   0.000000
4         67.897541         86.700740  25.36572  222.798212   0.000000

   km_vialidad_urbana     km_total  n_federal_offices  no_n_federal_offices
0         1873.548644  3004.866873                133                     0
1           30.652053   410.013174                 13                     0
2           56.450543   574.066726                154                     0
3           43.043676   185.919289                  6                     0
4          310.238861   762.100377                  9                     0

[5 rows x 76 columns]

In [36]:
merged.to_csv("merged_covariates.csv", index=False)

# Merging part 3

In [37]:
aero = pd.read_csv("data/covariates/aerodrome_counts_full.csv")
drainage = pd.read_csv("data/covariates/water_drainage.csv")
capital_distance = pd.read_csv("data/covariates/municipality_capital_distances.csv")
mun_infrastructure = pd.read_csv("data/covariates/municipality_infrastructure_summary.csv")
pemex = pd.read_csv("data/covariates/municipality_pemex_distances.csv")
rail = pd.read_csv("data/covariates/municipality_rail_summary.csv")

In [38]:
print("-----AERO HEAD------")
print(aero.head())

print("-----DRAINAGE HEAD------")
print(drainage.head())

print("-----CAPITAL DISTANCE HEAD------")
print(capital_distance.head())

print("-----MUNICIPALITY INFRASTRUCTURE HEAD------")
print(mun_infrastructure.head())

print("-----PEMEX HEAD------")
print(pemex.head())

print("-----RAILWAY HEAD------")
print(rail.head())

-----AERO HEAD------
   CVEGEO                     NOMGEO  n_aerodromes  no_n_aerodromes  \
0    1005                Jesús María             0                1
1    1008         San José de Gracia             0                1
2    1001             Aguascalientes             0                0
3    1004                      Cosío             0                1
4    1011  San Francisco de los Romo             0                1

   n_heliports  no_n_heliports  has_aerodrome  has_heliport
0            0               1              0             0
1            0               1              0             0
2            1               0              0             1
3            0               1              0             0
4            0               1              0             0
-----DRAINAGE HEAD------
   CVEGEO  ag_servi  no_ag_servi  pobl_prc  no_pobl_prc  ag_dias  no_ag_dias  \
0    1001       1.0            0     99.00            0     0.00           1
1    1002       1.0            0     75.00            0     0.00           1
2    1003       1.0            0     97.85            0     5.90           0
3    1004       1.0            0     98.00            0     6.25           0
4    1005       1.0            0     98.00            0     0.00           1

    ag_horas  no_ag_horas  serv_dre  no_serv_dre  dren_cab  no_dren_cab  \
0   0.000000            1       1.0            0     98.35            0
1   0.000000            1       1.0            0     85.00            0
2   8.466667            0       1.0            0      0.00            1
3  12.583333            0       1.0            0     98.00            0
4   0.000000            1       1.0            0     96.00            0

   dren_plu  no_dren_plu tot_conx  no_tot_conx  prest_nu  no_prest_nu
0       2.0            0   347981            0       1.0            0
1       2.0            0    13800            0       1.0            0
2       2.0            0    19790            0       1.0            0
3       2.0            0     4670            0       1.0            0
4       1.0            0    37015            0       1.0            0
-----CAPITAL DISTANCE HEAD------
   CVEGEO  state_num      state_name     own_capital  capital_cvegeo  \
0    1005          1  Aguascalientes  Aguascalientes            1001
1    1008          1  Aguascalientes  Aguascalientes            1001
2    1001          1  Aguascalientes  Aguascalientes            1001
3    1004          1  Aguascalientes  Aguascalientes            1001
4    1011          1  Aguascalientes  Aguascalientes            1001

   dist_cap_own  dist_capmun_own  dist_cap_nearest     nearest_cap  \
0     17.471019        21.148358         17.471019  Aguascalientes
1     38.561498        44.999609         38.561498  Aguascalientes
2      8.148609         0.000000          8.148609  Aguascalientes
3     52.349442        60.485366         52.349442  Aguascalientes
4     17.429608        25.291198         17.429608  Aguascalientes

  nearest_cap_state  same_state_cap  is_capital  near_own_cap  \
0    Aguascalientes            True       False          True
1    Aguascalientes            True       False          True
2    Aguascalientes            True        True          True
3    Aguascalientes            True       False         False
4    Aguascalientes            True       False          True

   excess_dist_own_cap  log_dist_cap_own  n_caps_100km  n_caps_200km
0                  0.0          2.916203             2             5
1                  0.0          3.677856             2             5
2                  0.0          2.213602             1             5
3                  0.0          3.976864             2             4
4                  0.0          2.913958             2             5
-----MUNICIPALITY INFRASTRUCTURE HEAD------
   CVEGEO          NOMGEO  n_sites_total  n_aduana  n_puerto  \
0    1001  Aguascalientes            266         0         0
1    1002        Asientos             16         0         0
2    1003        Calvillo             37         0         0
3    1004           Cosío              8         0         0
4    1005     Jesús María             43         0         0

   n_puerto_fronterizo  n_terminal_multimodal  n_estacion_ferrocarril  \
0                    0                      0                       0
1                    0                      0                       0
2                    0                      0                       0
3                    0                      0                       0
4                    0                      0                       0

   n_zona_industrial  n_almacen  ...  has_puerto  has_puerto_fronterizo  \
0                  0          0  ...           0                      0
1                  0          0  ...           0                      0
2                  0          0  ...           0                      0
3                  0          0  ...           0                      0
4                  0          0  ...           0                      0

   has_aeropuerto  has_aeropuerto_internacional  has_estacion_ferrocarril  \
0               1                             1                         0
1               0                             0                         0
2               0                             0                         0
3               0                             0                         0
4               0                             0                         0

   has_terminal_multimodal  has_zona_industrial  has_atractivo_turistico  \
0                        0                    0                        1
1                        0                    0                        1
2                        0                    0                        1
3                        0                    0                        0
4                        0                    0                        1

   has_hotel  has_tourism
0          0            1
1          0            1
2          0            1
3          0            0
4          0            1

[5 rows x 74 columns]
-----PEMEX HEAD------
   CVEGEO  dist_gasproc_cent nearest_gasproc_cent  n_gasproc_25km_cent  \
0    1005         475.336021          CPG Arenque                    0
1    1008         481.129847          CPG Arenque                    0
2    1001         460.711600          CPG Arenque                    0
3    1004         457.286992          CPG Arenque                    0
4    1011         451.603577          CPG Arenque                    0

   n_gasproc_50km_cent  n_gasproc_100km_cent  dist_maritime_cent  \
0                    0                     0          370.820047
1                    0                     0          388.408598
2                    0                     0          368.340998
3                    0                     0          419.282218
4                    0                     0          392.271150

  nearest_maritime_cent  n_maritime_25km_cent  n_maritime_50km_cent  ...  \
0         TM Manzanillo                     0                     0  ...
1         TM Manzanillo                     0                     0  ...
2         TM Manzanillo                     0                     0  ...
3         TM Manzanillo                     0                     0  ...
4         TM Manzanillo                     0                     0  ...

   nearest_storage_edge  n_storage_25km_edge n_storage_50km_edge  \
0    TAR Aguascalientes                    1                   1
1    TAR Aguascalientes                    1                   2
2    TAR Aguascalientes                    1                   1
3         TAR Zacatecas                    0                   2
4    TAR Aguascalientes                    1                   1

   n_storage_100km_edge  dist_any_edge  n_any_25km_edge  n_any_50km_edge  \
0                     2       6.284716                1                1
1                     2      19.408291                1                2
2                     3       0.000000                1                1
3                     2      40.445016                0                2
4                     2       7.352846                1                1

  n_any_100km_edge  n_hosted  hosts_any
0                2         0      False
1                2         0      False
2                3         1       True
3                2         0      False
4                2         0      False

[5 rows x 61 columns]
-----RAILWAY HEAD------
   CVEGEO          NOMGEO  km_ferrocarril_total  km_ferrocarril_operacion  \
0    1001  Aguascalientes             47.835129                 47.835129
1    1002        Asientos             22.680147                 22.680147
2    1003        Calvillo              0.000000                  0.000000
3    1004           Cosío             19.162775                 19.162775
4    1005     Jesús María              2.835592                  2.835592

   km_ferrocarril_sin_uso  km_ferrocarril_carga  km_ferrocarril_pasajeros  \
0                     0.0             47.835129                       0.0
1                     0.0             22.680147                       0.0
2                     0.0              0.000000                       0.0
3                     0.0             19.162775                       0.0
4                     0.0              2.835592                       0.0

   km_ferrocarril_carga_pasajeros  km_ferrocarril_inactivo  km_ferromex  ...  \
0                             0.0                      0.0    35.183526  ...
1                             0.0                      0.0     0.000000  ...
2                             0.0                      0.0     0.000000  ...
3                             0.0                      0.0    19.162775  ...
4                             0.0                      0.0     2.835592  ...

   km_jalisco  km_mexico_toluca  km_ferrocarril_suburbano  km_puebla  \
0         0.0               0.0                       0.0        0.0
1         0.0               0.0                       0.0        0.0
2         0.0               0.0                       0.0        0.0
3         0.0               0.0                       0.0        0.0
4         0.0               0.0                       0.0        0.0

   km_sin_concesion  has_ferrocarril  has_ferrocarril_operacion  \
0               0.0                1                          1
1               0.0                1                          1
2               0.0                0                          0
3               0.0                1                          1
4               0.0                1                          1

   has_ferrocarril_carga  has_ferrocarril_pasajeros  \
0                      1                          0
1                      1                          0
2                      0                          0
3                      1                          0
4                      1                          0

   has_ferrocarril_carga_pasajeros
0                                0
1                                0
2                                0
3                                0
4                                0

[5 rows x 27 columns]

In [39]:
aero = aero.drop(columns = ['NOMGEO'])
mun_infrastructure = mun_infrastructure.drop(columns = ['NOMGEO'])
rail = rail.drop(columns = ['NOMGEO'])

In [40]:
print(aero["CVEGEO"].nunique())
print(drainage["CVEGEO"].nunique())
print(capital_distance["CVEGEO"].nunique())
print(mun_infrastructure["CVEGEO"].nunique())
print(pemex["CVEGEO"].nunique())
print(rail["CVEGEO"].nunique())

2478
2478
2478
2478
2478
2478

In [41]:
aero['CVEGEO'] = aero['CVEGEO'].astype(str).str.zfill(5)
drainage['CVEGEO'] = drainage['CVEGEO'].astype(str).str.zfill(5)
capital_distance['CVEGEO'] = capital_distance['CVEGEO'].astype(str).str.zfill(5)
mun_infrastructure['CVEGEO'] = mun_infrastructure['CVEGEO'].astype(str).str.zfill(5)
pemex['CVEGEO'] = pemex['CVEGEO'].astype(str).str.zfill(5)
rail['CVEGEO'] = rail['CVEGEO'].astype(str).str.zfill(5)

In [42]:
merged_final = merged.merge(aero, on="CVEGEO", how="outer") \
           .merge(drainage, on="CVEGEO", how="outer") \
           .merge(mun_infrastructure, on="CVEGEO", how="outer") \
           .merge(pemex, on="CVEGEO", how="outer") \
           .merge(rail, on="CVEGEO", how="outer")

In [43]:
print(merged_final.head())

  CVEGEO          NOMGEO  homicidio_doloso_2025  robo_veh_violencia_2025  \
0  01001  Aguascalientes                   41.0                     47.0
1  01002        Asientos                    3.0                     10.0
2  01003        Calvillo                    0.0                      2.0
3  01004           Cosío                    2.0                      7.0
4  01005     Jesús María                   15.0                     16.0

   n_inseguro_popw      tdpa_avg  no_tdpa_avg  punto_generador_count  \
0     264703.23100  11298.763489            0                   30.0
1      20111.86968   4616.674641            0                   10.0
2      14514.80605   4997.627660            0                   11.0
3              NaN   6973.539568            0                    3.0
4      48465.88493  11065.404598            0                   16.0

   no_punto_generador_count     m_avg  ...  km_jalisco  km_mexico_toluca  \
0                         0  2.917626  ...         0.0               0.0
1                         0  5.194737  ...         0.0               0.0
2                         0  2.532979  ...         0.0               0.0
3                         0  3.200719  ...         0.0               0.0
4                         0  2.894713  ...         0.0               0.0

   km_ferrocarril_suburbano  km_puebla  km_sin_concesion  has_ferrocarril  \
0                       0.0        0.0               0.0                1
1                       0.0        0.0               0.0                1
2                       0.0        0.0               0.0                0
3                       0.0        0.0               0.0                1
4                       0.0        0.0               0.0                1

   has_ferrocarril_operacion  has_ferrocarril_carga  \
0                          1                      1
1                          1                      1
2                          0                      0
3                          1                      1
4                          1                      1

   has_ferrocarril_pasajeros  has_ferrocarril_carga_pasajeros
0                          0                                0
1                          0                                0
2                          0                                0
3                          0                                0
4                          0                                0

[5 rows x 257 columns]

In [44]:
merged_final.columns.to_list()

['CVEGEO',
 'NOMGEO',
 'homicidio_doloso_2025',
 'robo_veh_violencia_2025',
 'n_inseguro_popw',
 'tdpa_avg',
 'no_tdpa_avg',
 'punto_generador_count',
 'no_punto_generador_count',
 'm_avg',
 'no_m_avg',
 'a_avg',
 'no_a_avg',
 'b_avg',
 'no_b_avg',
 'c2_avg',
 'no_c2_avg',
 'c3_avg',
 'no_c3_avg',
 't3s2_avg',
 'no_t3s2_avg',
 't3s3_avg',
 'no_t3s3_avg',
 't3s2r4_avg',
 'no_t3s2r4_avg',
 'otros_avg',
 'no_otros_avg',
 'aa_avg',
 'no_aa_avg',
 'bb_avg',
 'no_bb_avg',
 'cc_avg',
 'no_cc_avg',
 'IM_2020',
 'no_IM_2020',
 'IE',
 'no_IE',
 'TCVCU',
 'no_TCVCU',
 'ICE',
 'no_ICE',
 'VIVPAR_HAB',
 'no_VIVPAR_HAB',
 'POBTOT',
 'no_POBTOT',
 'pct_VPH_SINTIC',
 'no_pct_VPH_SINTIC',
 'pct_VPH_C_ELEC',
 'no_pct_VPH_C_ELEC',
 'pct_VPH_AGUADV',
 'no_pct_VPH_AGUADV',
 'pct_VPH_PISODT',
 'no_pct_VPH_PISODT',
 'pct_VPH_PISOTI',
 'no_pct_VPH_PISOTI',
 'pct_VPH_1CUART',
 'no_pct_VPH_1CUART',
 'n_schools_avg',
 'no_n_schools_avg',
 'pct_con_bebederos',
 'no_pct_con_bebederos',
 'pct_con_proteccion_civil',
 'no_pct_con_proteccion_civil',
 'pct_con_cancha',
 'no_pct_con_cancha',
 'avg_anio_creacion',
 'no_avg_anio_creacion',
 'km_carretera_fed',
 'km_carretera_est',
 'km_cuota',
 'km_camino',
 'km_vereda',
 'km_vialidad_urbana',
 'km_total',
 'n_federal_offices',
 'no_n_federal_offices',
 'n_aerodromes',
 'no_n_aerodromes',
 'n_heliports',
 'no_n_heliports',
 'has_aerodrome',
 'has_heliport',
 'ag_servi',
 'no_ag_servi',
 'pobl_prc',
 'no_pobl_prc',
 'ag_dias',
 'no_ag_dias',
 'ag_horas',
 'no_ag_horas',
 'serv_dre',
 'no_serv_dre',
 'dren_cab',
 'no_dren_cab',
 'dren_plu',
 'no_dren_plu',
 'tot_conx',
 'no_tot_conx',
 'prest_nu',
 'no_prest_nu',
 'n_sites_total',
 'n_aduana',
 'n_puerto',
 'n_puerto_fronterizo',
 'n_terminal_multimodal',
 'n_estacion_ferrocarril',
 'n_zona_industrial',
 'n_almacen',
 'n_zona_libre',
 'n_aeropuerto',
 'n_aeropuerto_internacional',
 'n_pista_aerea',
 'n_muelle_embarcadero',
 'n_terminal_transbordador',
 'n_central_camionera',
 'n_estacion_pesaje',
 'n_caseta_inspeccion',
 'n_estacion_combustible',
 'n_estacion_policia',
 'n_oficina_gobierno',
 'n_palacio_gobierno',
 'n_palacio_justicia',
 'n_estacion_bomberos',
 'n_hospital',
 'n_emergencia_medica',
 'n_primeros_auxilios',
 'n_universidad',
 'n_centro_investigacion',
 'n_atractivo_turistico',
 'n_hotel_motel',
 'n_museo',
 'n_monumento_historico',
 'n_centro_cultural',
 'n_centro_convenciones',
 'n_lugar_esparcimiento',
 'n_mirador',
 'n_parque_diversiones',
 'n_parque_animal',
 'n_campo_golf',
 'n_restaurante',
 'n_balneario',
 'n_ex_hacienda',
 'n_presa_turistica',
 'n_area_natural_protegida',
 'n_zona_arqueologica',
 'n_lago_laguna',
 'n_cascada',
 'n_pueblo_magico',
 'n_cenote',
 'n_gruta',
 'n_ruinas',
 'n_teleferico_funicular',
 'n_museo_historia',
 'n_museo_arte',
 'n_museo_ciencia',
 'n_museo_ninos',
 'n_turismo_historico',
 'n_turismo_natural',
 'n_turismo_cultural',
 'n_turismo_recreativo',
 'n_turismo_total',
 'has_aduana',
 'has_puerto',
 'has_puerto_fronterizo',
 'has_aeropuerto',
 'has_aeropuerto_internacional',
 'has_estacion_ferrocarril',
 'has_terminal_multimodal',
 'has_zona_industrial',
 'has_atractivo_turistico',
 'has_hotel',
 'has_tourism',
 'dist_gasproc_cent',
 'nearest_gasproc_cent',
 'n_gasproc_25km_cent',
 'n_gasproc_50km_cent',
 'n_gasproc_100km_cent',
 'dist_maritime_cent',
 'nearest_maritime_cent',
 'n_maritime_25km_cent',
 'n_maritime_50km_cent',
 'n_maritime_100km_cent',
 'dist_petrochem_cent',
 'nearest_petrochem_cent',
 'n_petrochem_25km_cent',
 'n_petrochem_50km_cent',
 'n_petrochem_100km_cent',
 'dist_refinery_cent',
 'nearest_refinery_cent',
 'n_refinery_25km_cent',
 'n_refinery_50km_cent',
 'n_refinery_100km_cent',
 'dist_storage_cent',
 'nearest_storage_cent',
 'n_storage_25km_cent',
 'n_storage_50km_cent',
 'n_storage_100km_cent',
 'dist_any_cent',
 'n_any_25km_cent',
 'n_any_50km_cent',
 'n_any_100km_cent',
 'dist_gasproc_edge',
 'nearest_gasproc_edge',
 'n_gasproc_25km_edge',
 'n_gasproc_50km_edge',
 'n_gasproc_100km_edge',
 'dist_maritime_edge',
 'nearest_maritime_edge',
 'n_maritime_25km_edge',
 'n_maritime_50km_edge',
 'n_maritime_100km_edge',
 'dist_petrochem_edge',
 'nearest_petrochem_edge',
 'n_petrochem_25km_edge',
 'n_petrochem_50km_edge',
 'n_petrochem_100km_edge',
 'dist_refinery_edge',
 'nearest_refinery_edge',
 'n_refinery_25km_edge',
 'n_refinery_50km_edge',
 'n_refinery_100km_edge',
 'dist_storage_edge',
 'nearest_storage_edge',
 'n_storage_25km_edge',
 'n_storage_50km_edge',
 'n_storage_100km_edge',
 'dist_any_edge',
 'n_any_25km_edge',
 'n_any_50km_edge',
 'n_any_100km_edge',
 'n_hosted',
 'hosts_any',
 'km_ferrocarril_total',
 'km_ferrocarril_operacion',
 'km_ferrocarril_sin_uso',
 'km_ferrocarril_carga',
 'km_ferrocarril_pasajeros',
 'km_ferrocarril_carga_pasajeros',
 'km_ferrocarril_inactivo',
 'km_ferromex',
 'km_kcs_mexico',
 'km_ferrosur',
 'km_tren_maya',
 'km_istmo_tehuantepec',
 'km_coahuila_durango',
 'km_ferrorvalle',
 'km_tijuana_tecate',
 'km_jalisco',
 'km_mexico_toluca',
 'km_ferrocarril_suburbano',
 'km_puebla',
 'km_sin_concesion',
 'has_ferrocarril',
 'has_ferrocarril_operacion',
 'has_ferrocarril_carga',
 'has_ferrocarril_pasajeros',
 'has_ferrocarril_carga_pasajeros']

In [45]:
merged_final.to_csv("merged_covariates.csv", index=False)

In [46]:
import pandas as pd 
import os
os.chdir("/Users/alexanakanishi/Desktop/harris-data-analytics/harris-week7")
print(os.getcwd())
df = pd.read_csv("merged_covariates.csv")

/Users/alexanakanishi/Desktop/harris-data-analytics/harris-week7

In [47]:
print(df['CVEGEO'].nunique())

2478

# Checking my vs austin ranking

In [64]:
my_rank = pd.read_csv("composite_index.csv")
all_rank = pd.read_csv("all_three_ranks.csv")
austin_rank = pd.read_csv("data/w7_strategic19_zcomp.csv")

In [65]:
print(my_rank.head())
print("------------")
print(all_rank.head())
print('------------')
print(austin_rank.head())

   clave_ent         entidad  CVEGEO       municipio  \
0          1  Aguascalientes    1001  Aguascalientes
1          1  Aguascalientes    1002        Asientos
2          1  Aguascalientes    1003        Calvillo
3          1  Aguascalientes    1004          Cos√≠o
4          1  Aguascalientes    1005   Jes√∫s Mar√≠a

   homicidio_doloso_prom_diario  robo_veh_violencia_prom_diario  \
0                      0.112329                        0.128767
1                      0.008219                        0.027397
2                      0.000000                        0.005479
3                      0.005479                        0.019178
4                      0.041096                        0.043836

   nom_mun_envipe  n_muestra_percepcion  pct_inseguro_municipio  \
0  AGUASCALIENTES                1305.0                0.402567
1        ASIENTOS                 106.0                0.627868
2        CALVILLO                  83.0                0.379224
3             NaN                   NaN                     NaN
4     JESUS MARIA                 144.0                0.578304

   n_inseguro_popw  non_sampled  z_homicidio  z_robo_veh  z_inseguro  \
0     264703.23100            0     0.811721    0.338147    3.107720
1      20111.86968            0    -0.123969   -0.058803   -0.007869
2      14514.80605            0    -0.197839   -0.144631   -0.079164
3          0.00000            1    -0.148592   -0.090989   -0.264052
4      48465.88493            0     0.171512    0.005567    0.353303

   composite  rank_composite
0   1.419196              63
1  -0.063547             476
2  -0.140544             751
3  -0.167878             953
4   0.176794             241
------------
   CVEGEO            municipio  rank_composite  rank_pca  rank_lda
0   25006            Culiac√°n               1         1         1
1    2004              Tijuana               2         2         2
2   15033  Ecatepec de Morelos               3         3         3
3    8037              Ju√°rez               4         4         4
4   11020                Le√≥n               6         6         5
------------
   CVEGEO                                          municipio  \
0    2005                                 Playas de Rosarito
1   21154                                       Tecamachalco
2   11014  Dolores Hidalgo Cuna de la Independencia Nacional
3   23004                                    Othón P. Blanco
4   30102                               Martínez de la Torre

                           entidad  strategic_target  stratum  rank_final  \
0                  Baja California                 1     2005         150
1                           Puebla                 0     2005         149
2                       Guanajuato                 0     2005         151
3                     Quintana Roo                 0     2005         152
4  Veracruz de Ignacio de la Llave                 0     2005         153

   score  r_hom  r_rob  r_surveypopw
0  0.491     72    177         295.0
1  0.492    174     72         251.0
2  0.488    126    122         171.0
3  0.486    211    379          96.0
4  0.481     93    381         158.0

# Merging with composite rankings

In [66]:
treated = pd.read_csv("data/treated61-2.csv")
print(treated)

    CVEGEO          entidad              municipio  gov_inclusion_code
0     2004  Baja California                Tijuana  homdol_rvcv_percep
1     6002           Colima                 Colima              homdol
2    12001         Guerrero     Acapulco de Juárez         homdol_rvcv
3    25006          Sinaloa               Culiacán  homdol_rvcv_percep
4    26018           Sonora                 Cajeme              homdol
..     ...              ...                    ...                 ...
56   24013  San Luis Potosí          Ciudad Valles           strategic
57   26055           Sonora  San Luis Rio Colorado           strategic
58   31050          Yucatán                 Mérida           strategic
59   31041          Yucatán                Kanasín           strategic
60   32010        Zacatecas              Fresnillo           strategic

[61 rows x 4 columns]

In [ ]:

merged_with_rank = df.merge(my_rank[["CVEGEO", "rank_composite", "composite"]], on="CVEGEO", how="left")
merged_with_rank = merged_with_rank.merge(austin_rank[["CVEGEO", "strategic_target"]], on="CVEGEO", how="left")

# pulling in strategically selected municipalities
merged_with_rank["strategic_target"] = merged_with_rank["strategic_target"].fillna(0).astype(int)

print(merged_with_rank)

      CVEGEO                 NOMGEO  homicidio_doloso_2025  \
0       1001         Aguascalientes                   41.0
1       1002               Asientos                    3.0
2       1003               Calvillo                    0.0
3       1004                  Cosío                    2.0
4       1005            Jesús María                   15.0
...      ...                    ...                    ...
2473   32054          Villa Hidalgo                    0.0
2474   32055             Villanueva                   18.0
2475   32056              Zacatecas                    6.0
2476   32057               Trancoso                    1.0
2477   32058  Santa María de la Paz                    0.0

      robo_veh_violencia_2025  n_inseguro_popw      tdpa_avg  no_tdpa_avg  \
0                        47.0    264703.231000  11298.763489            0
1                        10.0     20111.869680   4616.674641            0
2                         2.0     14514.806050   4997.627660            0
3                         7.0              NaN   6973.539568            0
4                        16.0     48465.884930  11065.404598            0
...                       ...              ...           ...          ...
2473                      1.0      8768.466667      0.000000            1
2474                     43.0     18820.097110   3579.824074            0
2475                     29.0     82131.583120  14772.376190            0
2476                      2.0              NaN   5066.540000            0
2477                      0.0              NaN      0.000000            1

      punto_generador_count  no_punto_generador_count     m_avg  ...  \
0                      30.0                         0  2.917626  ...
1                      10.0                         0  5.194737  ...
2                      11.0                         0  2.532979  ...
3                       3.0                         0  3.200719  ...
4                      16.0                         0  2.894713  ...
...                     ...                       ...       ...  ...
2473                    0.0                         1  0.000000  ...
2474                    3.0                         0  1.638889  ...
2475                   11.0                         0  1.960377  ...
2476                    2.0                         0  1.020000  ...
2477                    0.0                         1  0.000000  ...

      km_puebla  km_sin_concesion  has_ferrocarril  has_ferrocarril_operacion  \
0           0.0               0.0                1                          1
1           0.0               0.0                1                          1
2           0.0               0.0                0                          0
3           0.0               0.0                1                          1
4           0.0               0.0                1                          1
...         ...               ...              ...                        ...
2473        0.0               0.0                1                          1
2474        0.0               0.0                0                          0
2475        0.0               0.0                1                          1
2476        0.0               0.0                0                          0
2477        0.0               0.0                0                          0

      has_ferrocarril_carga  has_ferrocarril_pasajeros  \
0                         1                          0
1                         1                          0
2                         0                          0
3                         1                          0
4                         1                          0
...                     ...                        ...
2473                      1                          0
2474                      0                          0
2475                      1                          0
2476                      0                          0
2477                      0                          0

      has_ferrocarril_carga_pasajeros  rank_composite  composite  \
0                                   0              63   1.419196
1                                   0             476  -0.063547
2                                   0             751  -0.140544
3                                   0             953  -0.167878
4                                   0             241   0.176794
...                               ...             ...        ...
2473                                0             965  -0.168519
2474                                0             244   0.172098
2475                                0             191   0.292357
2476                                0            1331  -0.193966
2477                                0            1826  -0.209326

      strategic_target
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
2473                 0
2474                 0
2475                 0
2476                 0
2477                 0

[2478 rows x 260 columns]

In [72]:
print(merged_with_rank['strategic_target'].nunique())

2

In [74]:
merged_with_rank["treated"] = merged_with_rank["CVEGEO"].isin(treated["CVEGEO"]).astype(int)

In [76]:
print(merged_with_rank)
print(merged_with_rank['treated'].nunique())

      CVEGEO                 NOMGEO  homicidio_doloso_2025  \
0       1001         Aguascalientes                   41.0
1       1002               Asientos                    3.0
2       1003               Calvillo                    0.0
3       1004                  Cosío                    2.0
4       1005            Jesús María                   15.0
...      ...                    ...                    ...
2473   32054          Villa Hidalgo                    0.0
2474   32055             Villanueva                   18.0
2475   32056              Zacatecas                    6.0
2476   32057               Trancoso                    1.0
2477   32058  Santa María de la Paz                    0.0

      robo_veh_violencia_2025  n_inseguro_popw      tdpa_avg  no_tdpa_avg  \
0                        47.0    264703.231000  11298.763489            0
1                        10.0     20111.869680   4616.674641            0
2                         2.0     14514.806050   4997.627660            0
3                         7.0              NaN   6973.539568            0
4                        16.0     48465.884930  11065.404598            0
...                       ...              ...           ...          ...
2473                      1.0      8768.466667      0.000000            1
2474                     43.0     18820.097110   3579.824074            0
2475                     29.0     82131.583120  14772.376190            0
2476                      2.0              NaN   5066.540000            0
2477                      0.0              NaN      0.000000            1

      punto_generador_count  no_punto_generador_count     m_avg  ...  \
0                      30.0                         0  2.917626  ...
1                      10.0                         0  5.194737  ...
2                      11.0                         0  2.532979  ...
3                       3.0                         0  3.200719  ...
4                      16.0                         0  2.894713  ...
...                     ...                       ...       ...  ...
2473                    0.0                         1  0.000000  ...
2474                    3.0                         0  1.638889  ...
2475                   11.0                         0  1.960377  ...
2476                    2.0                         0  1.020000  ...
2477                    0.0                         1  0.000000  ...

      km_sin_concesion  has_ferrocarril  has_ferrocarril_operacion  \
0                  0.0                1                          1
1                  0.0                1                          1
2                  0.0                0                          0
3                  0.0                1                          1
4                  0.0                1                          1
...                ...              ...                        ...
2473               0.0                1                          1
2474               0.0                0                          0
2475               0.0                1                          1
2476               0.0                0                          0
2477               0.0                0                          0

      has_ferrocarril_carga  has_ferrocarril_pasajeros  \
0                         1                          0
1                         1                          0
2                         0                          0
3                         1                          0
4                         1                          0
...                     ...                        ...
2473                      1                          0
2474                      0                          0
2475                      1                          0
2476                      0                          0
2477                      0                          0

      has_ferrocarril_carga_pasajeros  rank_composite  composite  \
0                                   0              63   1.419196
1                                   0             476  -0.063547
2                                   0             751  -0.140544
3                                   0             953  -0.167878
4                                   0             241   0.176794
...                               ...             ...        ...
2473                                0             965  -0.168519
2474                                0             244   0.172098
2475                                0             191   0.292357
2476                                0            1331  -0.193966
2477                                0            1826  -0.209326

      strategic_target  treated
0                    0        0
1                    0        0
2                    0        0
3                    0        0
4                    0        0
...                ...      ...
2473                 0        0
2474                 0        0
2475                 0        0
2476                 0        0
2477                 0        0

[2478 rows x 261 columns]
2

In [77]:
cols = merged_with_rank.columns.tolist()
cols.remove("rank_composite")
cols.insert(4, "rank_composite")
cols.remove("composite")
cols.insert(5, "composite")
cols.remove("treated")
cols.insert(2, "treated")
cols.remove("strategic_target")
cols.insert(3, "strategic_target")
merged_with_rank = merged_with_rank[cols]

In [78]:
print(merged_with_rank)

      CVEGEO                 NOMGEO  treated  strategic_target  \
0       1001         Aguascalientes        0                 0
1       1002               Asientos        0                 0
2       1003               Calvillo        0                 0
3       1004                  Cosío        0                 0
4       1005            Jesús María        0                 0
...      ...                    ...      ...               ...
2473   32054          Villa Hidalgo        0                 0
2474   32055             Villanueva        0                 0
2475   32056              Zacatecas        0                 0
2476   32057               Trancoso        0                 0
2477   32058  Santa María de la Paz        0                 0

      homicidio_doloso_2025  robo_veh_violencia_2025  rank_composite  \
0                      41.0                     47.0              63
1                       3.0                     10.0             476
2                       0.0                      2.0             751
3                       2.0                      7.0             953
4                      15.0                     16.0             241
...                     ...                      ...             ...
2473                    0.0                      1.0             965
2474                   18.0                     43.0             244
2475                    6.0                     29.0             191
2476                    1.0                      2.0            1331
2477                    0.0                      0.0            1826

      composite  n_inseguro_popw      tdpa_avg  ...  km_jalisco  \
0      1.419196    264703.231000  11298.763489  ...         0.0
1     -0.063547     20111.869680   4616.674641  ...         0.0
2     -0.140544     14514.806050   4997.627660  ...         0.0
3     -0.167878              NaN   6973.539568  ...         0.0
4      0.176794     48465.884930  11065.404598  ...         0.0
...         ...              ...           ...  ...         ...
2473  -0.168519      8768.466667      0.000000  ...         0.0
2474   0.172098     18820.097110   3579.824074  ...         0.0
2475   0.292357     82131.583120  14772.376190  ...         0.0
2476  -0.193966              NaN   5066.540000  ...         0.0
2477  -0.209326              NaN      0.000000  ...         0.0

      km_mexico_toluca  km_ferrocarril_suburbano  km_puebla  km_sin_concesion  \
0                  0.0                       0.0        0.0               0.0
1                  0.0                       0.0        0.0               0.0
2                  0.0                       0.0        0.0               0.0
3                  0.0                       0.0        0.0               0.0
4                  0.0                       0.0        0.0               0.0
...                ...                       ...        ...               ...
2473               0.0                       0.0        0.0               0.0
2474               0.0                       0.0        0.0               0.0
2475               0.0                       0.0        0.0               0.0
2476               0.0                       0.0        0.0               0.0
2477               0.0                       0.0        0.0               0.0

      has_ferrocarril  has_ferrocarril_operacion  has_ferrocarril_carga  \
0                   1                          1                      1
1                   1                          1                      1
2                   0                          0                      0
3                   1                          1                      1
4                   1                          1                      1
...               ...                        ...                    ...
2473                1                          1                      1
2474                0                          0                      0
2475                1                          1                      1
2476                0                          0                      0
2477                0                          0                      0

      has_ferrocarril_pasajeros  has_ferrocarril_carga_pasajeros
0                             0                                0
1                             0                                0
2                             0                                0
3                             0                                0
4                             0                                0
...                         ...                              ...
2473                          0                                0
2474                          0                                0
2475                          0                                0
2476                          0                                0
2477                          0                                0

[2478 rows x 261 columns]

In [79]:
## EXPORTING DF WITH RANK TO CSV
merged_with_rank.to_csv("merged_covariates_with_rank.csv", index=False)

In [57]:
merged_with_rank[merged_with_rank['CVEGEO'] == "09998"]

Empty DataFrame
Columns: [CVEGEO, NOMGEO, rank_composite, homicidio_doloso_2025, robo_veh_violencia_2025, n_inseguro_popw, tdpa_avg, no_tdpa_avg, punto_generador_count, no_punto_generador_count, m_avg, no_m_avg, a_avg, no_a_avg, b_avg, no_b_avg, c2_avg, no_c2_avg, c3_avg, no_c3_avg, t3s2_avg, no_t3s2_avg, t3s3_avg, no_t3s3_avg, t3s2r4_avg, no_t3s2r4_avg, otros_avg, no_otros_avg, aa_avg, no_aa_avg, bb_avg, no_bb_avg, cc_avg, no_cc_avg, IM_2020, no_IM_2020, IE, no_IE, TCVCU, no_TCVCU, ICE, no_ICE, VIVPAR_HAB, no_VIVPAR_HAB, POBTOT, no_POBTOT, pct_VPH_SINTIC, no_pct_VPH_SINTIC, pct_VPH_C_ELEC, no_pct_VPH_C_ELEC, pct_VPH_AGUADV, no_pct_VPH_AGUADV, pct_VPH_PISODT, no_pct_VPH_PISODT, pct_VPH_PISOTI, no_pct_VPH_PISOTI, pct_VPH_1CUART, no_pct_VPH_1CUART, n_schools_avg, no_n_schools_avg, pct_con_bebederos, no_pct_con_bebederos, pct_con_proteccion_civil, no_pct_con_proteccion_civil, pct_con_cancha, no_pct_con_cancha, avg_anio_creacion, no_avg_anio_creacion, km_carretera_fed, km_carretera_est, km_cuota, km_camino, km_vereda, km_vialidad_urbana, km_total, n_federal_offices, no_n_federal_offices, n_aerodromes, no_n_aerodromes, n_heliports, no_n_heliports, has_aerodrome, has_heliport, ag_servi, no_ag_servi, pobl_prc, no_pobl_prc, ag_dias, no_ag_dias, ag_horas, no_ag_horas, serv_dre, no_serv_dre, dren_cab, no_dren_cab, dren_plu, no_dren_plu, tot_conx, no_tot_conx, prest_nu, ...]
Index: []

[0 rows x 258 columns]